### PR TITLE
MySpeed: Fix build step

### LINKED ISSUE #8424: Cant install MySpeed
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

MyScript

### 📂 What was the exact command used to execute the script?

bash -c "$(curl -fsSL https://git.community-scripts.org/community-scripts/ProxmoxVE/raw/branch/main/ct/myspeed.sh)"

### ⚙️ What settings are you using?

- [x] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 13

### 📈 Which Proxmox version are you on?

9.0.11

### 📝 Provide a clear and concise description of the issue.

Hello,

I tried to install MySpeed LXC, but during the final steps, I received this error message.
`  ✔️   IPv4 Internet Connected
  ✔️   IPv6 Internet Connected
  ✔️   Git DNS: github.com:(✔️ ) raw.githubusercontent.com:(✔️ ) api.github.com:(✔️ ) git.community-scripts.org:(✔️ )
  ✔️   Updated Container OS
  ✔️   Installed Dependencies
  ✔️   Setup Node.js 22
  ✔️   Deployed: myspeed (1.0.9)
⠇ Configuring MySpeed
[ERROR] in line 159: exit code 0: while executing command "$@" > /dev/null 2>&1

[ERROR] in line 1345: exit code 0: while executing command lxc-attach -n "$CTID" -- bash -c "$(curl -fsSL https://git.community-scripts.org/community-scripts/ProxmoxVE/raw/branch/main/install/${var_install}.sh)"
`

### 🔄 Steps to reproduce the issue.

1. Install Container

### ❌ Paste the full error output (if available).

[ERROR] in line 159: exit code 0: while executing command "$@" > /dev/null 2>&1

[ERROR] in line 1345: exit code 0: while executing command lxc-attach -n "$CTID" -- bash -c "$(curl -fsSL https://git.community-scripts.org/community-scripts/ProxmoxVE/raw/branch/main/install/${var_install}.sh)"
`

### 🖼️ Additional context (optional).

_No response_

### PR DESCRIPTION
**Pull request by tremor021**
## ✍️ Description  
- Added missing python dependency preventing the build stage to complete

## 🔗 Related PR / Issue  
Link: #8424

## ✅ Prerequisites  (**X** in brackets) 

- [x] **Self-review completed** – Code follows project standards.  
- [x] **Tested thoroughly** – Changes work as expected.  
- [x] **No security risks** – No hardcoded secrets, unnecessary privilege escalations, or permission issues.  

---

## 🛠️ Type of Change (**X** in brackets)  

- [x] 🐞 **Bug fix** – Resolves an issue without breaking functionality.  
- [ ] ✨ **New feature** – Adds new, non-breaking functionality.  
- [ ] 💥 **Breaking change** – Alters existing functionality in a way that may require updates.  
- [ ] 🆕 **New script** – A fully functional and tested script or script set.  
- [ ] 🌍 **Website update** – Changes to website-related JSON files or metadata.  
- [ ] 🔧 **Refactoring / Code Cleanup** – Improves readability or maintainability without changing functionality.  
- [ ] 📝 **Documentation update** – Changes to `README`, `AppName.md`, `CONTRIBUTING.md`, or other docs.

### CODE REVIEW

**Review by michelroegl-brunner — DISMISSED** [review]

File: install/myspeed-install.sh [hunk 1]
```diff
@@ -16,11 +16,12 @@ update_os
...
 $STD apt install -y \
   build-essential \
-  ca-certificates
+  ca-certificates \
+  python3-setuptools
 msg_ok "Installed Dependencies"
 
 NODE_VERSION="22" setup_nodejs
-fetch_and_deploy_gh_release "myspeed" "gnmyt/myspeed" "prebuild" "latest" "/opt/myspeed" "MySpeed-*.zip"
+fetch_and_deploy_gh_release "myspeed" "npm " "prebuild" "latest" "/opt/myspeed" "MySpeed-*.zip"
```
Comment (MickLesk) [inline install/myspeed-install.sh]: What?

**Review by MickLesk — CHANGES_REQUESTED** [review]

File: install/myspeed-install.sh (hunk 1 above)
Comment (michelroegl-brunner) [reply install/myspeed-install.sh]: Oh yes, i missed that.

**Review by michelroegl-brunner — APPROVED** [review]

**Review by MickLesk — APPROVED** [review]
