### PR TITLE
Patch Netbird Script | Container Boot-Check | Debian/Ubuntu Only

### LINKED ISSUE #335: Netbird script does not work on alpine containers
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

it is not possibile to install netbird on a container alpine_linux-based

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Alpine

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```
Installing NetBird...
bash: line 3: /usr/share/keyrings/netbird-archive-keyring.gpg: No such file or directory
wget: write error: Broken pipe
bash: line 4: /etc/apt/sources.list.d/netbird.list: No such file or directory
```

### Please provide detailed steps to reproduce the issue.

try to install a container based on alpine linux. 
then try to install netbird client on this container and you get the following error after the menu where you select where to install netbird
```

    _   __     __  ____  _          __
   / | / /__  / /_/ __ )(_)________/ /
  /  |/ / _ \/ __/ __  / / ___/ __  /
 / /|  /  __/ /_/ /_/ / / /  / /_/ /
/_/ |_/\___/\__/_____/_/_/   \__,_/

Installing NetBird...
bash: line 3: /usr/share/keyrings/netbird-archive-keyring.gpg: No such file or directory
wget: write error: Broken pipe
bash: line 4: /etc/apt/sources.list.d/netbird.list: No such file or directory
```

### PR DESCRIPTION
**Pull request by MickLesk**
## Description
- Added a check if the container is stopped -> starting it
- Added a check for debian/ubuntu -> if not, script exit (alpine not allowed)
- Update Documentation on website

Fixes #335 

## Type of change
Please check the relevant option(s):

- [x] Bug fix (non-breaking change that resolves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (a fix or feature that would cause existing functionality to change unexpectedly)
- [ ] New script (a fully functional and thoroughly tested script or set of scripts.)

## Prerequisites
The following efforts must be made for the PR to be considered. Please check when completed:
- [x] Self-review performed (I have reviewed my code, ensuring it follows established patterns and conventions)
- [x] Testing performed (I have tested my changes, ensuring everything works as expected)
- [x] Documentation updated (I have updated any relevant documentation)

### CODE REVIEW

File: misc/add-netbird-lxc.sh [hunk 1]
```diff
@@ -1,7 +1,8 @@
 #!/usr/bin/env bash
 
-# Copyright (c) 2021-2024 tteck
+# Copyright (c) 2021-2024 community-scripts ORG
```
Comment (havardthom) [inline misc/add-netbird-lxc.sh:3]: image

File: misc/add-netbird-lxc.sh [hunk 2]
```diff
@@ -52,6 +54,23 @@ while [ -z "${CTID:+x}" ]; do
     "${CTID_MENU[@]}" 3>&1 1>&2 2>&3) || exit
 done
 
+LXC_STATUS=$(pct status "$CTID" | awk '{print $2}')
```
Comment (havardthom) [inline misc/add-netbird-lxc.sh:57]: This check is done like this in other scripts such as `clean-lxcs.sh`, `update-lxcs.sh`, `update-lxcs-cron.sh`
```
    status=$(pct status $container)
    template=$(pct config $container | grep -q "template:" && echo "true" || echo "false")
    if [ "$template" == "false" ] && [ "$status" == "status: stopped" ]; then
      echo -e "${BL}[Info]${GN} Starting${BL} $container ${CL} \n"
      pct start $container
      echo -e "${BL}[Info]${GN} Waiting For${BL} $container${CL}${GN} To Start ${CL} \n"
      sleep 5
      clean_container $container
      echo -e "${BL}[Info]${GN} Shutting down${BL} $container ${CL} \n"
      pct shutdown $container &
    elif [ "$status" == "status: running" ]; then
      clean_container $container
    fi
```

Perhaps there should be an `install_netbird` function so it can be implemented in a similar manner

Comment (MickLesk) [reply misc/add-netbird-lxc.sh:57]: Then you have to completely revert the script again. It hardly adheres to any conventions anyway. I have rather less desire ^^ that's how it works in any case 😜

Comment (havardthom) [reply misc/add-netbird-lxc.sh:57]: I would atleast use this part instead of a `while` loop, since it can end up as a neverending loop if something goes wrong
```
echo -e "${BL}[Info]${GN} Waiting For${BL} $container${CL}${GN} To Start ${CL} \n"
sleep 5
```

Comment (MickLesk) [reply misc/add-netbird-lxc.sh:57]: I have tested installing this block, but it doesn't fit at all. The changeover for this to work is too big for me to do it. The whole script and the process would have to be adapted. It works like this in any case, even on absolutely undersized servers. If you're tired, close the PR and customize it yourself :smile:
