### PR TITLE
SuwayomiServer: Bump Java to v21, code formating

### LINKED ISSUE #3983: Suwayomi Server Install/Update Bug
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Suwayomi-Server

### 📂 What was the exact command used to execute the script?

bash -c "$(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/ct/suwayomiserver.sh)"

### ⚙️ What settings are you using?

- [x] Default Settings
- [x] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 📝 Provide a clear and concise description of the issue.

The Debian package for the latest Suwayomi Server release (Suwayomi-Server-v2.0.1727-debian-all.deb), released approximately 5 days ago (around April 17th, 2025), has a declared dependency on openjdk-21-jre.

When attempting to install this package using dpkg -i, the installation fails with the following error:

dpkg: dependency problems prevent configuration of suwayomi-server:
 suwayomi-server depends on openjdk-21-jre; however:
  Package openjdk-21-jre is not installed.

dpkg: error processing package suwayomi-server (--install):
 dependency problems - leaving unconfigured

### 🔄 Steps to reproduce the issue.

Scenario 1: Clean Installation on a New Debian LXC Container

Create a new, clean Debian LXC container in Proxmox.
Download the latest Suwayomi Server Debian package (Suwayomi-Server-v2.0.1727-debian-all.deb).
Attempt to install it using sudo dpkg -i Suwayomi-Server-v2.0.1727-debian-all.deb.
Observe the dependency error indicating that openjdk-21-jre is not installed, and the installation fails.

Scenario 2: Attempting to Upgrade an Existing Suwayomi Server Installation (Potentially)

Have a Proxmox LXC container with a previous version of Suwayomi Server installed (which was likely running on openjdk-17-jre or similar).
Attempt to upgrade the Suwayomi Server by downloading and installing the new .deb package using sudo dpkg -i Suwayomi-Server-v2.0.1727-debian-all.deb.
Observe the dependency error indicating that openjdk-21-jre is required but not satisfied, potentially halting the upgrade process.

So i got stuck, and used a debian container and i create the server manually using the bundle.

thank you for your help!

### ❌ Paste the full error output (if available).

dpkg: dependency problems prevent configuration of suwayomi-server:
 suwayomi-server depends on openjdk-21-jre; however:
  Package openjdk-21-jre is not installed.

dpkg: error processing package suwayomi-server (--install):
 dependency problems - leaving unconfigured

### 🖼️ Additional context (optional).

_No response_

### PR DESCRIPTION
**Pull request by tremor021**
## ✍️ Description  
- Replace OpenJDK 17 with Temurin 21
- Code formating

## 🔗 Related PR / Issue  
Link: #3983 

## ✅ Prerequisites  (**X** in brackets) 

- [x] **Self-review completed** – Code follows project standards.  
- [x] **Tested thoroughly** – Changes work as expected.  
- [x] **No security risks** – No hardcoded secrets, unnecessary privilege escalations, or permission issues.  

---

## 🛠️ Type of Change (**X** in brackets)  

- [x] 🐞 **Bug fix** – Resolves an issue without breaking functionality.  
- [ ] ✨ **New feature** – Adds new, non-breaking functionality.  
- [ ] 💥 **Breaking change** – Alters existing functionality in a way that may require updates.  
- [ ] 🆕 **New script** – A fully functional and tested script or script set.  
- [ ] 🌍 **Website update** – Changes to website-related JSON files or metadata.  
- [x] 🔧 **Refactoring / Code Cleanup** – Improves readability or maintainability without changing functionality.  
- [ ] 📝 **Documentation update** – Changes to `README`, `AppName.md`, `CONTRIBUTING.md`, or other docs.

### CODE REVIEW

**Review by MickLesk — APPROVED** [review]

**Comment by MickLesk** [comment]
Look this Script really for an fixed package? Dumb. Maybe we need to create an issue there. Jdk21 is jdk21, what an bullshit ^^

**Comment by tremor021** [comment]
Yea, thats really weird

**Comment by CrazyWolf13** [comment]
https://github.com/Suwayomi/Suwayomi-Server/issues/1352

File: ct/suwayomiserver.sh [hunk 1]
```diff
@@ -20,38 +20,46 @@ color
...
+    msg_error "No ${APP} Installation Found!"
     exit
+  fi
+  if dpkg -l | grep -q "openjdk-17-jre"; then
+    $STD apt-get remove -y openjdk-17-jre
+    mkdir -p /etc/apt/keyrings
+    curl -fsSL "https://packages.adoptium.net/artifactory/api/gpg/key/public" | gpg --dearmor >/etc/apt/trusted.gpg.d/adoptium.gpg
+    echo "deb https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" >/etc/apt/sources.list.d/adoptium.list
+    $STD apt-get update
+    $STD apt-get install -y temurin-21-jre
```
Comment (MickLesk) [inline ct/suwayomiserver.sh:37]: JAVA_VERSION=21 install_java

File: ct/suwayomiserver.sh [hunk 2]
```diff
@@ -20,38 +20,46 @@ color
...
+  RELEASE=$(curl -fsSL https://api.github.com/repos/Suwayomi/Suwayomi-Server/releases/latest | grep "tag_name" | awk '{print substr($2, 2, length($2)-3) }')
+  if [[ "${RELEASE}" != "$(cat /opt/suwayomi-server_version.txt)" ]] || [[ ! -f /opt/suwayomi-server_version.txt ]]; then
+    msg_info "Updating $APP"
+    msg_info "Stopping $APP"
+    systemctl stop suwayomi-server
+    msg_ok "Stopped $APP"
+    msg_info "Updating $APP to v${RELEASE}"
+    cd /tmp
+    URL=$(curl -fsSL https://api.github.com/repos/Suwayomi/Suwayomi-Server/releases/latest | grep "browser_download_url" | awk '{print substr($2, 2, length($2)-2) }' | tail -n+2 | head -n 1)
+    curl -fsSL "$URL" -o $(basename "$URL")
```
Comment (MickLesk) [inline ct/suwayomiserver.sh:48]: Why is this so different from other current installations?

File: ct/suwayomiserver.sh [hunk 3]
```diff
@@ -20,38 +20,46 @@ color
...
+    $STD dpkg -i /tmp/*.deb
```
Comment (MickLesk) [inline ct/suwayomiserver.sh:49]: wildcard here maybe bad, because if break something or user download deb packages into temp

File: ct/suwayomiserver.sh [hunk 4]
```diff
@@ -20,38 +20,46 @@ color
...
+    msg_ok "Updated $APP to v${RELEASE}"
+    msg_info "Starting $APP"
+    systemctl start suwayomi-server
+    msg_ok "Started $APP"
+    msg_info "Cleaning Up"
+    rm -f *.deb
```
Comment (MickLesk) [inline ct/suwayomiserver.sh:55]: look line 49 comment

File: install/suwayomiserver-install.sh [hunk 5]
```diff
@@ -14,17 +14,23 @@ network_check
...
 
+msg_info "Setting up Adoptium Repository"
+mkdir -p /etc/apt/keyrings
+curl -fsSL "https://packages.adoptium.net/artifactory/api/gpg/key/public" | gpg --dearmor >/etc/apt/trusted.gpg.d/adoptium.gpg
+echo "deb https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" >/etc/apt/sources.list.d/adoptium.list
+$STD apt-get update
+msg_ok "Set up Adoptium Repository"
+
 msg_info "Settting up Suwayomi-Server"
+$STD apt-get install -y temurin-21-jre
```
Comment (MickLesk) [inline install/suwayomiserver-install.sh:28]: JAVA_VERSION=21 install_java

**Review by MickLesk — CHANGES_REQUESTED** [review]

**Review by michelroegl-brunner — DISMISSED** [review]

**Review by MickLesk — APPROVED** [review]

**Review by michelroegl-brunner — APPROVED** [review]
