### PR TITLE
n8n: Fix dependencies

### LINKED ISSUE #11430: [n8n] Missing dependency 'graphicsmagick' causes "Edit Image" node errors
### Discussed in https://github.com/community-scripts/ProxmoxVE/discussions/11418

<div type='discussions-op-text'>

<sup>Originally posted by **14790897** February  1, 2026</sup>

### Script
n8n LXC

### Issue Description
I installed n8n using the Proxmox VE Helper-Script. When attempting to use the **"Edit Image"** node within n8n workflows, the execution fails with an error indicating that the `gm` binary is missing.

It seems the `graphicsmagick` package is not included in the default installation script, which is required for n8n's image processing nodes.

### Error Message
```text
Could not execute GraphicsMagick/ImageMagick: gm "identify" "-ping" "-verbose" "-" this most likely means the gm/convert binaries can't be found

```

### Solution / Workaround

I was able to fix this manually by entering the LXC console and running:

```bash
apt-get update
apt-get install -y graphicsmagick

```

After installing the package and restarting n8n, the "Edit Image" node works correctly.

</div>

### PR DESCRIPTION
**Pull request by tremor021**
## ✍️ Description
- Now requires `graphicsmagick`

## 🔗 Related Issue

Fixes #11430 

## ✅ Prerequisites (**X** in brackets)

- [x] **Self-review completed** – Code follows project standards.
- [x] **Tested thoroughly** – Changes work as expected.
- [x] **No security risks** – No hardcoded secrets, unnecessary privilege escalations, or permission issues.

---

## 🛠️ Type of Change (**X** in brackets)

- [x] 🐞 **Bug fix** – Resolves an issue without breaking functionality.
- [ ] ✨ **New feature** – Adds new, non-breaking functionality.
- [ ] 💥 **Breaking change** – Alters existing functionality in a way that may require updates.
- [ ] 🆕 **New script** – A fully functional and tested script or script set.
- [ ] 🌍 **Website update** – Changes to website-related JSON files or metadata.
- [ ] 🔧 **Refactoring / Code Cleanup** – Improves readability or maintainability without changing functionality.
- [ ] 📝 **Documentation update** – Changes to `README`, `AppName.md`, `CONTRIBUTING.md`, or other docs.

### CODE REVIEW

File: ct/n8n.sh [hunk 1]
```diff
@@ -27,6 +27,9 @@ function update_script() {
     msg_error "No ${APP} Installation Found!"
     exit
   fi
+  if ! dpkg -s graphicsmagick >/dev/null 2>&1; then
+    $STD apt install -y graphicsmagick
+  fi
```
Comment (CrazyWolf13) [inline ct/n8n.sh]:
```suggestion
ensure_dependencies graphicsmagick
```

**Review by CrazyWolf13 — CHANGES_REQUESTED** [review]

**Review by MickLesk — APPROVED** [review]

**Review by CrazyWolf13 — APPROVED** [review]
