### PR TITLE
RDTClient Remove .NET 8.0 | Add .NET 9.0

### LINKED ISSUE #399: RDTClient update breaks web front end
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

While updating the RDTClient, previously had a version from tteck, using the update command in the LXC, it updates the RDTClient but breaks the front end presumably because of the wrong dotnet-sdk version.

Removing dotnet-sdk-8.0 and installing dotnet-sdk-9.0 fixed the problem. I found the solution [here](https://github.com/rogerfar/rdt-client/issues/611)

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

k

### Please provide detailed steps to reproduce the issue.

1. Coming from a previous version, using update command to update RDTClient
3. Reboot
4. Frontend broken

### PR DESCRIPTION
**Pull request by MickLesk**
## Description
Remove .NET 8 in CT.sh | Add .NET 9.0 in CT.sh
Change .NET Install to 9.0 in INSTALL.sh 

Fixes #399 

## Type of change
Please check the relevant option(s):

- [x] Bug fix (non-breaking change that resolves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (a fix or feature that would cause existing functionality to change unexpectedly)
- [ ] New script (a fully functional and thoroughly tested script or set of scripts.)

## Prerequisites
The following efforts must be made for the PR to be considered. Please check when completed:
- [x] Self-review performed (I have reviewed my code, ensuring it follows established patterns and conventions)
- [x] Testing performed (I have tested my changes, ensuring everything works as expected)
- [x] Documentation updated (I have updated any relevant documentation)

### CODE REVIEW

**Comment by havardthom** [comment]
[Please use correct syntax to link issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword):

Fixes https://github.com/community-scripts/ProxmoxVE/issues/399

File: ct/rdtclient.sh [hunk 1]
```diff
@@ -54,17 +54,33 @@ function default_settings() {
...
+check_container_storage
+check_container_resources
 if [[ ! -d /opt/rdtc/ ]]; then msg_error "No ${APP} Installation Found!"; exit; fi
-msg_info "Updating $APP"
+msg_info "Stopping ${APP}"
 systemctl stop rdtc
+msg_ok "Stopped ${APP}"
+
+msg_info "Updating ${APP}"
+if dpkg-query -W dotnet-sdk-8.0 >/dev/null 2>&1; then
```
Comment (havardthom) [inline ct/rdtclient.sh:65]: We use `apt-get` to install the package, should use the same when searching for it. 

Also not sure we should actually handle breaking changes and fixing dependencies like this in the update function. It can end up with a lot of `if` conditions. Can't we just fix `rdtclient-instal.sh``and mark it as a breaking change? Then people that wants to update from old script can install the new dependency manually

Comment (MickLesk) [reply ct/rdtclient.sh:65]: This makes no functional difference, except that it is easier to read and understand. The install is still done with apt-get, only the query for the package is done with dpkg. 

```bash
if apt list --installed dotnet-sdk-8.0 2>/dev/null | grep -q "^dotnet-sdk-8.0/"; then
    apt-get remove --purge -y dotnet-sdk-8.0
    apt-get install -y dotnet-sdk-9.0
fi
``` 

That could be done, but I'm already seeing the first bug reports because the front end doesn't work.

In addition, probably nobody looks at the documentation. I would probably set myself a reminder and remove this line of code in 6 months. Whoever still has the problem then is long overdue either way :-D

Comment (havardthom) [reply ct/rdtclient.sh:65]: Ok we can add it if you want. Then make a task in the github project to remove it in some months, so it is remembered. Also have to be marked as a breaking change when it is removed later then.

**Review by havardthom — APPROVED** [review]

**Review by newzealandpaul — APPROVED** [review]

**Comment by jwmann** [comment]
I ran this update and it at first failed. (ran `update` in LXC)
I ran it again and it was successful.

Now my rdt-client no longer works.
Rebooted the LXC and still doesn't work.
When I go to :6500, it says "Refused to Connect"

when I run `dotnet --info` it shows `8.0.10`

I didn't do anything else besides run this update

jwm-2024-11-25@1334

**Comment by MickLesk** [comment]
How do you have updated?

**Comment by jwmann** [comment]
> How do you have updated?

I ran `update` within the LXC Shell

`/usr/bin/update`

This is what `update` points to:
```
bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/rdtclient.sh)"
```

**Comment by havardthom** [comment]
What's the output if you run `dpkg-query -W dotnet-sdk-8.0` in LXC console?

**Comment by jwmann** [comment]
> dpkg-query -W dotnet-sdk-8.0

No packages found

jwm-2024-11-25@1442

**Comment by jwmann** [comment]
I ended up having to completely delete my container and start fresh to get my client working again.
