### PR TITLE
Debian13-VM: Optimize First Boot & add noCloud/Cloud Selection

### LINKED ISSUE #11807: Debian13 VM fails to load login prompt
### ✅ Have you read and understood the above guidelines?

yes

### 🔎 Did you run the script with verbose mode enabled?

Yes, verbose mode was enabled and the output is included below

### 📜 What is the name of the script you are using?

Debian 13

### 📂 What was the exact command used to execute the script?

bash -c "$(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/vm/debian-13-vm.sh)"

### ⚙️ What settings are you using?

- [x] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 13

### 📈 Which Proxmox version are you on?

9.1.5

### 📝 Provide a clear and concise description of the issue.

VMs created by the Debian13 script do not automatically load the login prompt after they boot, instead stalling after auditd checks. This can be circumvented by finishing the First Boot Wizard via the xterm.js serial console.

Notably, the issue only affects the latest two releases of Trixie (January 29 and February 10). If the qcow2 URL is changed to [the January 12 qcow2](https://cloud.debian.org/images/cloud/trixie/20260112-2355/debian-13-nocloud-amd64-20260112-2355.qcow2), the issue does not occur, suggesting a novel incompatibility.

### 🔄 Steps to reproduce the issue.

Step 1: Run `bash -c "$(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/vm/debian-13-vm.sh)"`
Step 2: Select `Yes` for both dialogs to set Default settings.
Step 3: Wait for VM to be created and command prompt to reappear
Step 4: Open console on new VM
Step 5: It stalls after auditd checks and doesn't load the login prompt.
Step 6: Opening a serial terminal with xterm.js shows that the VM is stuck in initial configuration. It prompts for TZ and root password, then finishes First Boot Wizard and loads the login prompt.

### ❌ Paste the full error output (if available).

No errors are thrown.

### 🖼️ Additional context (optional).

_No response_

### PR DESCRIPTION
**Pull request by MickLesk**
## ✍️ Description
migrated from dockerVM
- add cloudinit
- add noCloud/cloud selection
- virtcustomize if locale on host missing / add libguestsfs

## 🔗 Related Issue

Fixes #11807

## ✅ Prerequisites (**X** in brackets)

- [x] **Self-review completed** – Code follows project standards.
- [x] **Tested thoroughly** – Changes work as expected.
- [x] **No security risks** – No hardcoded secrets, unnecessary privilege escalations, or permission issues.

---

## 🛠️ Type of Change (**X** in brackets)

- [ ] 🐞 **Bug fix** – Resolves an issue without breaking functionality.
- [x] ✨ **New feature** – Adds new, non-breaking functionality.
- [ ] 💥 **Breaking change** – Alters existing functionality in a way that may require updates.
- [ ] 🆕 **New script** – A fully functional and tested script or script set.
- [ ] 🌍 **Website update** – Changes to website-related JSON files or metadata.
- [ ] 🔧 **Refactoring / Code Cleanup** – Improves readability or maintainability without changing functionality.
- [ ] 📝 **Documentation update** – Changes to `README`, `AppName.md`, `CONTRIBUTING.md`, or other docs.

### CODE REVIEW

**Review by tremor021 — APPROVED** [review]

File: vm/debian-13-vm.sh [hunk 1]
```diff
@@ -473,6 +477,17 @@ else
...
 msg_ok "Using ${CL}${BL}$STORAGE${CL} ${GN}for Storage Location."
 msg_ok "Virtual Machine ID is ${CL}${BL}$VMID${CL}."
+
+# ==============================================================================
+# PREREQUISITES
+# ==============================================================================
+if ! command -v virt-customize &>/dev/null; then
+  msg_info "Installing libguestfs-tools"
+  apt-get update >/dev/null 2>&1
+  apt-get install -y libguestfs-tools >/dev/null 2>&1
```
Comment (CrazyWolf13) [inline vm/debian-13-vm.sh:487]:
```suggestion
  $STD apt update
  $STD apt install -y libguestfs-tools 
```

Comment (michelroegl-brunner) [reply vm/debian-13-vm.sh:487]: $STD is not availible here? @MickLesk @CrazyWolf13

**Review by michelroegl-brunner — APPROVED** [review]

File: vm/debian-13-vm.sh (hunk 1 above)
Comment (MickLesk) [reply vm/debian-13-vm.sh:487]: correct

Comment (CrazyWolf13) [reply vm/debian-13-vm.sh:487]: @michelroegl-brunner ahh yeah my bad.
