### PR TITLE
Fix: AdventureLog - update script bug

### LINKED ISSUE #1331: [BUG] AdventureLog update does not update
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

AdventureLog

### 📂 What was the exact command used to execute the script?

update

### 📝 Provide a clear and concise description of the issue.

The adventurelog update script does not correctly update the script on the LXC.

### Issue in Update script
I have identified the issue to be in the update script.
This line: https://github.com/community-scripts/ProxmoxVE/blob/e1daaa6409d257314b29833bef1206da2f45aded/ct/adventurelog.sh#L47 

moves the folder AdventureLog-v.0.8.0 into the folder, but the intention is to update the files. 

### Comparison to other scripts
Other scripts either use tar to directly or unzip and then `rm -rf` the existing installation:
https://github.com/community-scripts/ProxmoxVE/blob/e1daaa6409d257314b29833bef1206da2f45aded/ct/wallos.sh#L44

or move the app to a backup location:
https://github.com/community-scripts/ProxmoxVE/blob/e1daaa6409d257314b29833bef1206da2f45aded/ct/part-db.sh#L43

### Caveats with AdentureLog
AdventureLog has user-generated data in `/opt/adventurelog` which needs to be migrated. I only found the `media` folder in the backend but there could be more. So these additional files have to be handled correctly.

### ⚙️ What settings are you using?

- [X] Default Settings
- [X] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

1. Install version 0.7.1.
2. Type `update`

### ❌ Paste the full error output (if available).

No error, just a non-updated app.

### 🖼️ Additional context (optional).

I technically used an advanced installation for a different number and I have changed the IP by hand as per the guide. This does not show in the fancy Proxmox information unfortunately.

But everything else is default.

### PR DESCRIPTION
**Pull request by JesperDramsch**
> **🛠️ Note:**  
> We are meticulous about merging code into the main branch, so please understand that pull requests not meeting the project's standards may be rejected. It's never personal!  
> 🎮 **Note for game-related scripts:** These have a lower likelihood of being merged.

---

## ✍️ Description
Adventure log wasn't updating correctly.

This fixes several things:

1. Move original installation into a backup location
2. Update installation
3. Move user-generated data back to installation (media and env files)
4. Return to PWD, which was left in the script and then files were left strewn around.

Fixes #1331

---

## 🛠️ Type of Change
Please check the relevant options:  
- [x] Bug fix (non-breaking change that resolves an issue)  
- [ ] New feature (non-breaking change that adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality to change unexpectedly)  
- [ ] New script (a fully functional and thoroughly tested script or set of scripts)  

---

## ✅ Prerequisites
The following steps must be completed for the pull request to be considered:  
- [x] Self-review performed (I have reviewed my code to ensure it follows established patterns and conventions.)  
- [x] Testing performed (I have thoroughly tested my changes and verified expected functionality.)  
- [x] Documentation updated (I have updated any relevant documentation)

---

## 📋 Additional Information (optional)
Provide any extra context or screenshots about the feature or fix here.  

I ran the code on my own installation. I made the design decision to keep prior files (sans media due to size) around as AdventureLog is changing quite a bit, which means I don't want to just `rm -rf` the old installation. But you can make the decision this would be more correct.

### CODE REVIEW

File: ct/adventurelog.sh [hunk 1]
```diff
@@ -34,29 +34,34 @@ function update_script() {
...
+    LAST_VERSION=$(cat /opt/${APP}_version.txt)
     msg_info "Stopping Services"
     systemctl stop adventurelog-backend
     systemctl stop adventurelog-frontend
     msg_ok "Services Stopped"
 
     msg_info "Updating ${APP} to ${RELEASE}"
-    cp /opt/adventurelog/backend/server/.env /opt/server.env
-    cp /opt/adventurelog/frontend/.env /opt/frontend.env
+    WORKDIR="$PWD"
```
Comment (michelroegl-brunner) [inline ct/adventurelog.sh:44]:
```suggestion
```
Not needed

File: ct/adventurelog.sh [hunk 2]
```diff
@@ -34,29 +34,34 @@ function update_script() {
...
     python3 manage.py migrate &>/dev/null
 
-    mv /opt/frontend.env /opt/adventurelog/frontend/.env
+
+    mv /opt/adventurelog-backup/frontend/.env /opt/adventurelog/frontend/.env
     cd /opt/adventurelog/frontend
     pnpm install &>/dev/null
     pnpm run build &>/dev/null
     echo "${RELEASE}" >/opt/${APP}_version.txt
+    cd "$WORKDIR"
```
Comment (michelroegl-brunner) [inline ct/adventurelog.sh:64]:
```suggestion
```
not needed

File: ct/adventurelog.sh [hunk 3]
```diff
@@ -66,6 +71,7 @@ function update_script() {
 
     msg_info "Cleaning Up"
     rm -rf v${RELEASE}.zip
+    mv /opt/adventurelog-backup/ adventurelog-backup-$LAST_VERSION/ # Keep backup, since AdventureLog moves quickly and we want to avoid breaking changes with rm -rf
```
Comment (michelroegl-brunner) [inline ct/adventurelog.sh:74]:
```suggestion
    rm -rf /opt/adventurelog-backup
```
We do not want to be responsible for user data backups. This should be done with lxc updates

**Review by michelroegl-brunner — CHANGES_REQUESTED** [review]

File: ct/adventurelog.sh (hunk 2 above)
Comment (JesperDramsch) [reply ct/adventurelog.sh:64]: @michelroegl-brunner the unremoved files during the clean-up step suggest that either this or a different handling of the downloaded zip file is needed.

File: ct/adventurelog.sh (hunk 3 above)
Comment (JesperDramsch) [reply ct/adventurelog.sh:74]: @michelroegl-brunner This is not directly about user backup. It's rather the thought that you, as maintainer of this community script, need to either be completely on top of changes within AdventureLogs that might introduce additional files that a user generates. Or you keep old versions after an update (or the secret third option, make some intelligent check).

This is not so much a backup, but rather an insurance policy that during an update you don't delete surprise files from a user (keep them retrievable).

File: ct/adventurelog.sh (hunk 1 above)
Comment (JesperDramsch) [reply ct/adventurelog.sh:44]: see below

File: ct/adventurelog.sh (hunk 3 above)
Comment (michelroegl-brunner) [reply ct/adventurelog.sh:74]: I´m working on more "global" approach for this issue atm. It will take a little bit of time. Should be a mix of your option " and 3.

File: ct/adventurelog.sh [hunk 4]
```diff
@@ -34,29 +34,34 @@ function update_script() {
...
     msg_ok "Services Stopped"
 
     msg_info "Updating ${APP} to ${RELEASE}"
-    cp /opt/adventurelog/backend/server/.env /opt/server.env
-    cp /opt/adventurelog/frontend/.env /opt/frontend.env
+    WORKDIR="$PWD"
+    mv /opt/adventurelog/ /opt/adventurelog-backup/
     wget -q "https://github.com/seanmorley15/AdventureLog/archive/refs/tags/v${RELEASE}.zip"
     unzip -q v${RELEASE}.zip
     mv AdventureLog-${RELEASE} /opt/adventurelog
```
Comment (michelroegl-brunner) [inline ct/adventurelog.sh:48]:
```suggestion
    wget -qO /opt/v${RELEASE}.zip "https://github.com/seanmorley15/AdventureLog/archive/refs/tags/v${RELEASE}.zip"
    unzip -q /opt/v${RELEASE}.zip
    mv /opt/AdventureLog-${RELEASE} /opt/adventurelog
```

File: ct/adventurelog.sh [hunk 5]
```diff
@@ -66,6 +71,7 @@ function update_script() {
 
     msg_info "Cleaning Up"
     rm -rf v${RELEASE}.zip
```
Comment (michelroegl-brunner) [inline ct/adventurelog.sh:73]:
```suggestion
    rm -rf /opt/v${RELEASE}.zip
```

File: ct/adventurelog.sh (hunk 2 above)
Comment (michelroegl-brunner) [reply ct/adventurelog.sh:64]: See my newest suggetions. This is how we handel this normaly. Now you know exactly where the files get downloaded to so you can delete it without knowing the PWD.

File: ct/adventurelog.sh (hunk 1 above)
Comment (michelroegl-brunner) [reply ct/adventurelog.sh:44]: see below

**Review by michelroegl-brunner — CHANGES_REQUESTED** [review]

File: ct/adventurelog.sh (hunk 3 above)
Comment (JesperDramsch) [reply ct/adventurelog.sh:72]: I'm quite nervous about entirely removing the old data. But if you say this will be fixed more elegantly, I'll put the responsibility on your shoulders. You're the maintainer, after all.

Comment (michelroegl-brunner) [reply ct/adventurelog.sh]: yes, the plan is to create a tarball everytime a update is done and store it at the lxc itself, so no user data will get lost. And also we can then revert changes if a update fails.

File: ct/adventurelog.sh [hunk 6]
```diff
@@ -34,25 +34,27 @@ function update_script() {
   fi
   RELEASE=$(curl -s https://api.github.com/repos/seanmorley15/AdventureLog/releases/latest | grep "tag_name" | awk '{print substr($2, 3, length($2)-4) }')
   if [[ ! -f /opt/${APP}_version.txt ]] || [[ "${RELEASE}" != "$(cat /opt/${APP}_version.txt)" ]]; then
+    LAST_VERSION=$(cat /opt/${APP}_version.txt)
```
Comment (michelroegl-brunner) [inline ct/adventurelog.sh:37]:
```suggestion
```
Not needed anymore.

**Review by michelroegl-brunner — CHANGES_REQUESTED** [review]

**Review by michelroegl-brunner — APPROVED** [review]

**Comment by MickLesk** [comment]
It's the same. Unless you have not updated the “update” call, then it still uses ttecks repo

**Comment by Solear** [comment]
The merged update does not work (LXC with adventurelog 7.0.1):

`  ✔️  Services Stopped
 ⠧mv: cannot stat '/opt/AdventureLog-0.8.0': No such file or directory

[ERROR] in line 46: exit code 0: while executing command mv /opt/AdventureLog-${RELEASE} /opt/adventurelog

root@adventurelog:~# cd /opt
root@adventurelog:/opt# ls
adventurelog-backup  AdventureLog_version.txt  v0.8.0.zip
root@adventurelog:/opt# `
