### PR TITLE
Kasm: Storing Creds Fix

### LINKED ISSUE #5160: KASM LXC - No creds generated after fresh install
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Kasm

### 📂 What was the exact command used to execute the script?

bash -c "$(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/ct/kasm.sh)"

### ⚙️ What settings are you using?

- [x] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 📝 Provide a clear and concise description of the issue.

After a fresh install with default settings, Kasm is installed but ~/kasm.creds is empty

### 🔄 Steps to reproduce the issue.

Fresh install and try to get the generated credentials

### ❌ Paste the full error output (if available).

Just empty credentials

### 🖼️ Additional context (optional).

_No response_

### PR DESCRIPTION
**Pull request by omiinaya**
## ✍️ Description  
Fixed a bug where the credential files would not be stored if verbose mode wasn't selected.

## 🔗 Related PR / Issue  
Link: #

## ✅ Prerequisites  (**X** in brackets) 

- [x] **Self-review completed** – Code follows project standards.  
- [x] **Tested thoroughly** – Changes work as expected.  
- [x] **No security risks** – No hardcoded secrets, unnecessary privilege escalations, or permission issues.  

---

## 🛠️ Type of Change (**X** in brackets)  

- [x] 🐞 **Bug fix** – Resolves an issue without breaking functionality.  
- [ ] ✨ **New feature** – Adds new, non-breaking functionality.  
- [ ] 💥 **Breaking change** – Alters existing functionality in a way that may require updates.  
- [ ] 🆕 **New script** – A fully functional and tested script or script set.  
- [ ] 🌍 **Website update** – Changes to website-related JSON files or metadata.  
- [ ] 🔧 **Refactoring / Code Cleanup** – Improves readability or maintainability without changing functionality.  
- [ ] 📝 **Documentation update** – Changes to `README`, `AppName.md`, `CONTRIBUTING.md`, or other docs.

### CODE REVIEW

**Comment by omiinaya** [comment]
seems @tremor021 beat me to it

File: install/kasm-install.sh [hunk 1]
```diff
@@ -19,15 +19,19 @@ curl -fsSL -o "/opt/kasm_release_${KASM_VERSION}.tar.gz" "https://kasm-static-co
...
-printf 'y\ny\ny\n4\n' | bash /opt/kasm_release/install.sh | tee ~/kasm-install.output
-sed -n '/Kasm UI Login Credentials/,$p' ~/kasm-install.output >~/kasm.creds
+printf 'y\ny\ny\n4\n' | bash /opt/kasm_release/install.sh > ~/kasm-install.output 2>&1
+cat ~/kasm-install.output | grep -A 20 -i "credentials\|login\|password\|admin" | sed '1i Kasm-Workspaces-Credentials' >~/kasm.creds
 msg_ok "Installed Kasm Workspaces"
 
 motd_ssh
 customize
 
+msg_info "Displaying Kasm Credentials"
```
Comment (CrazyWolf13) [inline install/kasm-install.sh:31]: each msg_info needs an msg_ok. either you use echo or add a msg_ok too.

**Review by CrazyWolf13 — DISMISSED** [review]

**Review by MickLesk — DISMISSED** [review]

**Review by michelroegl-brunner — DISMISSED** [review]

**Review by michelroegl-brunner — APPROVED** [review]

**Review by MickLesk — APPROVED** [review]
