### PR TITLE
GoMFT: Add frontend build procedure

### LINKED ISSUE #3448: GoMFT Update Fails
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

GoMFT

### 📂 What was the exact command used to execute the script?

update

### 📝 Provide a clear and concise description of the issue.

GoMFT update fails

### ⚙️ What settings are you using?

- [x] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

Run update within the container - get below error

### ❌ Paste the full error output (if available).

```
   ______      __  _______________
  / ____/___  /  |/  / ____/_  __/
 / / __/ __ \/ /|_/ / /_    / /   
/ /_/ / /_/ / /  / / __/   / /    
\____/\____/_/  /_/_/     /_/     
                                  

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
build-essential is already the newest version (12.9).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
  ✔️   Stopped GoMFT
⠙ Updating GoMFT to 0.2.1(!) templ version check: generator v0.3.857 is newer than templ version v0.3.833 found in go.mod file, consider running `go get -u github.com/a-h/templ` to upgrade
⠼ Updating GoMFT to 0.2.1(✓) Complete [ updates=88 duration=402.469733ms ]
⠏ Updating GoMFT to 0.2.1# github.com/starfleetcptn/gomft/components
components/admin_tools_templ.go:17:6: BackupFile redeclared in this block
        components/admin_database_templ.go:17:6: other declaration of BackupFile
components/admin_tools_templ.go:854:76: backup.ModTime undefined (type BackupFile has no field or method ModTime)

[ERROR] in line 53: exit code 0: while executing command $STD go build -o gomft
```

### 🖼️ Additional context (optional).

running 'update' or the full command is the same.

### PR DESCRIPTION
**Pull request by tremor021**
## ✍️ Description  
  
The application is now using NodeJS v20. We are adding a build procedure for the frontend.

## 🔗 Related PR / Issue  
Link: #3448 

## ✅ Prerequisites  (**X** in brackets) 

- [x] **Self-review completed** – Code follows project standards.  
- [x] **Tested thoroughly** – Changes work as expected.  
- [x] **No breaking changes** – Existing functionality remains intact.  
- [x] **No security risks** – No hardcoded secrets, unnecessary privilege escalations, or permission issues.  

---

## 🛠️ Type of Change (**X** in brackets)  

- [x] 🐞 **Bug fix** – Resolves an issue without breaking functionality.  
- [ ] ✨ **New feature** – Adds new, non-breaking functionality.  
- [ ] 💥 **Breaking change** – Alters existing functionality in a way that may require updates.  
- [ ] 🆕 **New script** – A fully functional and tested script or script set.  
- [ ] 🌍 **Website update** – Changes to website-related JSON files or metadata.  
- [x] 🔧 **Refactoring / Code Cleanup** – Improves readability or maintainability without changing functionality.  
- [ ] 📝 **Documentation update** – Changes to `README`, `AppName.md`, `CONTRIBUTING.md`, or other docs.  

---

## 🔍 Code & Security Review  (**X** in brackets) 

- [x] **Follows `Code_Audit.md` & `CONTRIBUTING.md` guidelines**

### CODE REVIEW

File: ct/gomft.sh [hunk 1]
```diff
@@ -32,7 +32,13 @@ function update_script() {
   if ! dpkg -l | grep -q "^ii.*build-essential"; then
     $STD apt-get install -y build-essential
   fi
-
+  if [[ ! -f "/usr/bin/node" ]]; then
+    mkdir -p /etc/apt/keyrings
+    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
+    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" >/etc/apt/sources.list.d/nodesource.list
```
Comment (MickLesk) [inline ct/gomft.sh:38]: 22 possible too?

File: install/gomft-install.sh [hunk 2]
```diff
@@ -32,15 +33,29 @@ ln -sf /usr/local/go/bin/go /usr/local/bin/go
 set -o pipefail
 msg_ok "Setup Golang"
 
+msg_info "Setting up Node.js Repository"
+mkdir -p /etc/apt/keyrings
+curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
+echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" >/etc/apt/sources.list.d/nodesource.list
```
Comment (MickLesk) [inline install/gomft-install.sh:39]: 22?

**Review by MickLesk — APPROVED** [review]

**Review by michelroegl-brunner — APPROVED** [review]
