### PR TITLE
Apache Guacamole: Install auth-jdbc component that matches release version

### LINKED ISSUE #5479: Guacamole LXC - Error when creating new user
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Apache Guacamole

### 📂 What was the exact command used to execute the script?

bash -c "$(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/ct/apache-guacamole.sh)"

### ⚙️ What settings are you using?

- [x] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 📝 Provide a clear and concise description of the issue.

After setting up the Guacamole LXC container based on the script, everything is working as expected initially. However, after creating a new user (beside the guacadmin account), the application becomes unusable, presenting an error:

Image

This issue can't be bypassed by rebooting the container and will represent itself no matter how many times you restart the container or the `guacd`, database, and tomcat service.

### 🔄 Steps to reproduce the issue.

1. Create the container as per the script using Default Settings.
2. Once Guacamole is running, login with the provided `guacadmin` user and go into settings to create a new user. Give the user any permission you like.
3. Log out, then log in with the new user.

### ❌ Paste the full error output (if available).

See above screenshot. I couldn't find any logs on the system indicating what might be happening.

### 🖼️ Additional context (optional).

_No response_

### PR DESCRIPTION
**Pull request by tremor021**
## ✍️ Description  
- Script now installs the auth-jdbc component that matches release version

## 🔗 Related PR / Issue  
Link: #5479 

## ✅ Prerequisites  (**X** in brackets) 

- [x] **Self-review completed** – Code follows project standards.  
- [x] **Tested thoroughly** – Changes work as expected.  
- [x] **No security risks** – No hardcoded secrets, unnecessary privilege escalations, or permission issues.  

---

## 🛠️ Type of Change (**X** in brackets)  

- [x] 🐞 **Bug fix** – Resolves an issue without breaking functionality.  
- [ ] ✨ **New feature** – Adds new, non-breaking functionality.  
- [ ] 💥 **Breaking change** – Alters existing functionality in a way that may require updates.  
- [ ] 🆕 **New script** – A fully functional and tested script or script set.  
- [ ] 🌍 **Website update** – Changes to website-related JSON files or metadata.  
- [ ] 🔧 **Refactoring / Code Cleanup** – Improves readability or maintainability without changing functionality.  
- [ ] 📝 **Documentation update** – Changes to `README`, `AppName.md`, `CONTRIBUTING.md`, or other docs.

### CODE REVIEW

**Review by MickLesk — DISMISSED** [review]

File: install/apache-guacamole-install.sh [hunk 1]
```diff
@@ -67,9 +67,9 @@ cd /root
 curl -fsSL "https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-8.0.26.tar.gz" -o "/root/mysql-connector-java-8.0.26.tar.gz"
```
Comment (CrazyWolf13) [inline install/apache-guacamole-install.sh]: needs bump to 9.3 too I think.

Comment (CrazyWolf13) [inline install/apache-guacamole-install.sh]: why does this actually use github release for server and apache for client, the apache server would contain the client too I think.

**Review by CrazyWolf13 — CHANGES_REQUESTED** [review]

File: install/apache-guacamole-install.sh (hunk 1 above)
Comment (stolp) [reply install/apache-guacamole-install.sh]: It is explicitly mentioned in the [documentation](https://guacamole.apache.org/doc/gug/mysql-auth.html) that this jar should be installed and downloaded.

The reason for this is, that the database connection is handled on the application server itself, thus not packaged inside the war archive.

Comment (stolp) [reply install/apache-guacamole-install.sh]: I don't think that this is necessary.

**Comment by stolp** [comment]
I think the script should continue to use ${RELEASE_SERVER} instead of $RELEASE_SERVER as added by this patch for reasons of consistency.

File: install/apache-guacamole-install.sh (hunk 1 above)
Comment (MickLesk) [reply install/apache-guacamole-install.sh]: its besser for security to have _up to date_  jdbc / odbc driver

**Review by MickLesk — APPROVED** [review]

**Review by CrazyWolf13 — APPROVED** [review]
