### PR TITLE
BentoPDF: replace http-server with nginx to fix WASM initialization timeout

### LINKED ISSUE #13619: BentoPDF
### ✅ Have you read and understood the above guidelines?

yes

### 🔎 Did you run the script with verbose mode enabled?

Yes, verbose mode was enabled and the output is included below

### 📜 What is the name of the script you are using?

BentoPDF

### 📂 What was the exact command used to execute the script?

bash -c "$(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/ct/bentopdf.sh)"

### ⚙️ What settings are you using?

- [x] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 13

### 📈 Which Proxmox version are you on?

8.4.14

### 📝 Provide a clear and concise description of the issue.

Hello, I am happily using BentoPDF on my own server but I've noticed that some of the tools are not working properly. I'm referring in particular to **Excel to PDF** and **Word to PDF**. If I try to convert a docx/xlsx files I end up with a WASM error.
Thank you for this great software and to the community-scripts team!

### 🔄 Steps to reproduce the issue.

- Open the tool Word to PDF (or Excel to PDF)
- Upload a file (I've tried with both docx and xlsx)
- Convert the file
- An error appears

### ❌ Paste the full error output (if available).

First the process get stuck at "Loading conversion engine (55%)..."

Image

Then I get an error

Image

Error
An error occurred during conversion. Error: WASM initialization timeout

### 🖼️ Additional context (optional).

- I'm trying with an extremely basic docx file (attached)
- I'm running BentoPDF 2.8.2 (I had the same issues on previous versions too)

[New.docx](https://github.com/user-attachments/files/26605346/New.docx)

### PR DESCRIPTION
**Pull request by MickLesk**
## ✍️ Description
- Replace \http-server\ with **nginx** as the static file server
- Configure a nginx site at \/etc/nginx/sites-available/bentopdf\ with the required \COOP\/\COEP\ headers (matching upstream)
- Add a **one-time migration** in \update_script\ so existing installations running the old \http-server\-based service are automatically migrated to nginx on next update

## 🔗 Related Issue

Fixes #13619

## ✅ Prerequisites (**X** in brackets)

- [x] **Self-review completed** – Code follows project standards.
- [x] **Tested thoroughly** – Changes work as expected.
- [x] **No security risks** – No hardcoded secrets, unnecessary privilege escalations, or permission issues.

---

## 🛠️ Type of Change (**X** in brackets)

- [ ] 🐞 **Bug fix** – Resolves an issue without breaking functionality.
- [x] ✨ **New feature** – Adds new, non-breaking functionality.
- [ ] 💥 **Breaking change** – Alters existing functionality in a way that may require updates.
- [ ] 🆕 **New script** – A fully functional and tested script or script set.
- [ ] 🌍 **Website update** – Changes to website-related JSON files or metadata.
- [ ] 🔧 **Refactoring / Code Cleanup** – Improves readability or maintainability without changing functionality.
- [ ] 📝 **Documentation update** – Changes to `README`, `AppName.md`, `CONTRIBUTING.md`, or other docs.

### CODE REVIEW

**Review by CrazyWolf13 — APPROVED** [review]

**Review by CrazyWolf13 — CHANGES_REQUESTED** [review]
block

**Comment by michelroegl-brunner** [comment]
why the block @CrazyWolf13

**Comment by MickLesk** [comment]
From me

**Review by michelroegl-brunner — DISMISSED** [review]

File: install/bentopdf-install.sh [hunk 1]
```diff
@@ -13,32 +13,105 @@ setting_up_container
 network_check
 update_os
 
+ensure_dependencies nginx openssl
```
Comment (CrazyWolf13) [inline install/bentopdf-install.sh]:
```suggestion
msg_info "Installing Dependencies"
$STD apt install -y \
  nginx \
  openssl
msg_ok "Installed Dependencies"
```

File: install/bentopdf-install.sh [hunk 2]
```diff
@@ -13,32 +13,105 @@ setting_up_container
...
 cp ./.env.example ./.env.production
 export NODE_OPTIONS="--max-old-space-size=3072"
 export SIMPLE_MODE=true
 export VITE_USE_CDN=true
 $STD npm run build:all
+if [[ ! -f /opt/bentopdf/dist/config.json ]]; then
+    cat <<'EOF' >/opt/bentopdf/dist/config.json
+{}
+EOF
+fi
```
Comment (CrazyWolf13) [inline install/bentopdf-install.sh]:
```suggestion
cat <<'EOF' >/opt/bentopdf/dist/config.json
{}
EOF
```

File: install/bentopdf-install.sh [hunk 3]
```diff
@@ -13,32 +13,105 @@ setting_up_container
...
 
 msg_info "Creating Service"
-cat <<EOF >/etc/systemd/system/bentopdf.service
+if [[ ! -f /etc/ssl/private/bentopdf-selfsigned.key || ! -f /etc/ssl/certs/bentopdf-selfsigned.crt ]]; then
+  CERT_CN="$(hostname -I | awk '{print $1}')"
+  $STD openssl req -x509 -nodes -newkey rsa:2048 -days 3650 \
+    -keyout /etc/ssl/private/bentopdf-selfsigned.key \
+    -out /etc/ssl/certs/bentopdf-selfsigned.crt \
+    -subj "/CN=${CERT_CN}"
+fi
```
Comment (CrazyWolf13) [inline install/bentopdf-install.sh]:
```suggestion
CERT_CN="$(hostname -I | awk '{print $1}')"
$STD openssl req -x509 -nodes -newkey rsa:2048 -days 3650 \
    -keyout /etc/ssl/private/bentopdf-selfsigned.key \
    -out /etc/ssl/certs/bentopdf-selfsigned.crt \
    -subj "/CN=${CERT_CN}"
```

**Review by CrazyWolf13 — CHANGES_REQUESTED** [review]

**Review by michelroegl-brunner — DISMISSED** [review]

**Review by CrazyWolf13 — APPROVED** [review]

**Review by michelroegl-brunner — APPROVED** [review]
