### PR TITLE
PocketID: Update PocketID for 2.x

### LINKED ISSUE #10498: Pocket ID V2.0.x broken after update
### ✅ Have you read and understood the above guidelines?

yes

### 🔎 Did you run the script with verbose mode enabled?

Yes, verbose mode was enabled and the output is included below

### 📜 What is the name of the script you are using?

Pocket ID

### 📂 What was the exact command used to execute the script?

update

### ⚙️ What settings are you using?

- [x] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 13

### 📈 Which Proxmox version are you on?

9.1.4

### 📝 Provide a clear and concise description of the issue.

The major update V2.0.X has a [breaking change](https://pocket-id.org/docs/setup/major-releases/migrate-v2), requiring the `ENCRYPTION_KEY` variable to be set in the `.env` file. Without it, Pocket ID won't start.
There are also other braking changes, but they seem not to affect my installation. Adding the `ENCRYPTION_KEY` made it work again

### 🔄 Steps to reproduce the issue.

1. Update LXC
2. See that Pocket ID won't start

### ❌ Paste the full error output (if available).

-

### 🖼️ Additional context (optional).

_No response_

### PR DESCRIPTION
**Pull request by tremor021**
## ✍️ Description
- v2.x introduced mandatory env var.

## 🔗 Related Issue

Fixes #10498 

## ✅ Prerequisites (**X** in brackets)

- [x] **Self-review completed** – Code follows project standards.
- [x] **Tested thoroughly** – Changes work as expected.
- [x] **No security risks** – No hardcoded secrets, unnecessary privilege escalations, or permission issues.

---

## 🛠️ Type of Change (**X** in brackets)

- [x] 🐞 **Bug fix** – Resolves an issue without breaking functionality.
- [ ] ✨ **New feature** – Adds new, non-breaking functionality.
- [ ] 💥 **Breaking change** – Alters existing functionality in a way that may require updates.
- [ ] 🆕 **New script** – A fully functional and tested script or script set.
- [ ] 🌍 **Website update** – Changes to website-related JSON files or metadata.
- [ ] 🔧 **Refactoring / Code Cleanup** – Improves readability or maintainability without changing functionality.
- [ ] 📝 **Documentation update** – Changes to `README`, `AppName.md`, `CONTRIBUTING.md`, or other docs.

### CODE REVIEW

File: ct/pocketid.sh [hunk 1]
```diff
@@ -29,6 +29,10 @@ function update_script() {
     exit
   fi
 
+  # Mandatory as of v2.x.x
+  ENCRYPTION_KEY=$(openssl rand -base64 32)
+  sed -i '/^ENCRYPTION_KEY=/!{ $a ENCRYPTION_KEY='"$ENCRYPTION_KEY"' }' /opt/pocket-id/.env
```
Comment (tomfrenzel) [inline ct/pocketid.sh]:
```suggestion
  sed -i -e '/^ENCRYPTION_KEY=/b' -e '$a ENCRYPTION_KEY='"$ENCRYPTION_KEY" /opt/pocket-id/.env
```

Your sed command command didn't work for me (operation not permitted error). I modified it to make it work

Comment (CrazyWolf13) [reply ct/pocketid.sh]: @tremor021

**Review by CrazyWolf13 — APPROVED** [review]

**Review by tomfrenzel — COMMENTED** [review]
Can confirm that it works now 👍🏽

**Review by MickLesk — APPROVED** [review]
