### PR TITLE
PowerDNS: use gsqlite3 backend instead of BIND

### LINKED ISSUE #12533: Non-functional PowerDNS
### ✅ Have you read and understood the above guidelines?

yes

### 🔎 Did you run the script with verbose mode enabled?

Yes, verbose mode was enabled and the output is included below

### 📜 What is the name of the script you are using?

PowerDNS

### 📂 What was the exact command used to execute the script?

bash -c "$(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/ct/powerdns.sh)"

### ⚙️ What settings are you using?

- [x] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 13

### 📈 Which Proxmox version are you on?

pve-manager/9.1.5/80cf92a64bef6889 (running kernel: 6.17.9-1-pve)

### 📝 Provide a clear and concise description of the issue.

After a fresh install using default settings, PowerDNS is non-functional. The `pdns_server` process starts and listens on port 53, but responds with `REFUSED` to all DNS queries, including zones created through the Poweradmin web interface.

The root cause is a backend mismatch: the install script sets up Poweradmin with a SQLite3 database (`/opt/poweradmin/powerdns.db`), but PowerDNS itself is configured with the **BIND backend** instead of **gsqlite3**. As a result, PowerDNS has no knowledge of any zones or records created through Poweradmin.

Specifically:

1. `/etc/powerdns/pdns.conf` contains `launch=` (empty), which overrides any `launch+=` directives in included files.
2. `/etc/powerdns/pdns.d/bind.conf` configures the BIND backend (`launch+=bind`), but this is ignored due to the empty `launch=` in the main config.
3. Even if the BIND backend were active, it would not read zones from the SQLite3 database that Poweradmin writes to.
4. The correct backend (`gsqlite3`) is installed (`pdns-backend-sqlite3` package is present) but never configured.

### 🔄 Steps to reproduce the issue.

1. Install PowerDNS LXC using the community script with default settings.
2. Open Poweradmin web interface and create a new Master zone (e.g., `example.com`).
3. Add SOA and NS records via Poweradmin.
4. Query the PowerDNS server:

```bash
dig @127.0.0.1 example.com SOA
```

5. Observe the response status is `REFUSED`.

### DNS query returns REFUSED

```
root@powerdns:~# dig @127.0.0.1 internal.example.com SOA

; <<>> DiG 9.20.18-1~deb13u1-Debian <<>> @127.0.0.1 internal.example.com SOA
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 36026
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232

;; QUESTION SECTION:
;internal.example.com.            IN      SOA

...
```

### PowerDNS config shows empty launch directive

```
root@powerdns:~# cat /etc/powerdns/pdns.conf | grep -v '^#' | grep -v '^$'
include-dir=/etc/powerdns/pdns.d
launch=
```

### BIND backend is configured but ineffective

```
root@powerdns:~# cat /etc/powerdns/pdns.d/bind.conf
# See https://doc.powerdns.com/authoritative/backends/bind.html
launch+=bind
```

### Manually switching to gsqlite3 also fails due to permissions

```
Mar 04 03:01:40 powerdns pdns_server[21307]: Caught an exception instantiating a backend (gsqlite3):
Unable to launch gsqlite3 connection: Failed to execute query: attempt to write a readonly database
```

### 🖼️ Additional context (optional).

The install script should:

1. **Remove the empty `launch=`** from `/etc/powerdns/pdns.conf` (or not set it in the first place), as it overrides any `launch+=` directives from included config files in `pdns.d/`.

2. **Replace the BIND backend config** (`/etc/powerdns/pdns.d/bind.conf`) with a gsqlite3 backend config pointing to the Poweradmin database:

```ini
launch=gsqlite3
gsqlite3-database=/opt/poweradmin/powerdns.db
```

3. **Set correct file permissions** so that the `pdns` user can read and write the SQLite database and its directory (required for WAL/journal files):

```bash
chown pdns:pdns /opt/poweradmin/powerdns.db
# Ensure pdns can write WAL/journal files in the same directory
```

Without these changes, the PowerDNS + Poweradmin setup is non-functional out of the box — PowerDNS cannot serve any zones created through the Poweradmin web UI.

### PR DESCRIPTION
**Pull request by MickLesk**
## ✍️ Description
- Comment out empty 'launch=' in pdns.conf that overrides launch+= directives
- Remove default bind.conf and create gsqlite3.conf pointing to the Poweradmin SQLite database (/opt/poweradmin/powerdns.db)
- Set correct ownership (pdns:pdns) and permissions (664) on the database file so pdns_server can read/write it
- Add www-data to pdns group for shared database access
- Restart pdns service alongside apache2

## 🔗 Related Issue

Fixes #12533

## ✅ Prerequisites (**X** in brackets)

- [x] **Self-review completed** – Code follows project standards.
- [ ] **Tested thoroughly** – Changes work as expected.
- [x] **No security risks** – No hardcoded secrets, unnecessary privilege escalations, or permission issues.

---

## 🛠️ Type of Change (**X** in brackets)

- [x] 🐞 **Bug fix** – Resolves an issue without breaking functionality.
- [ ] ✨ **New feature** – Adds new, non-breaking functionality.
- [ ] 💥 **Breaking change** – Alters existing functionality in a way that may require updates.
- [ ] 🆕 **New script** – A fully functional and tested script or script set.
- [ ] 🌍 **Website update** – Changes to website-related JSON files or metadata.
- [ ] 🔧 **Refactoring / Code Cleanup** – Improves readability or maintainability without changing functionality.
- [ ] 📝 **Documentation update** – Changes to `README`, `AppName.md`, `CONTRIBUTING.md`, or other docs.

### CODE REVIEW

File: install/powerdns-install.sh [hunk 1]
```diff
@@ -126,7 +132,10 @@ cat <<EOF >/etc/apache2/sites-enabled/poweradmin.conf
 EOF
 $STD a2enmod rewrite headers
 chown -R www-data:www-data /opt/poweradmin
-$STD systemctl restart apache2
+chown pdns:pdns /opt/poweradmin/powerdns.db
+chmod 664 /opt/poweradmin/powerdns.db
```
Comment (CrazyWolf13) [inline install/powerdns-install.sh:136]: on update script?

**Review by tremor021 — APPROVED** [review]

File: install/powerdns-install.sh (hunk 1 above)
Comment (MickLesk) [reply install/powerdns-install.sh:136]: no, for what?

**Review by CrazyWolf13 — APPROVED** [review]
