### PR TITLE
Coder-Code-Server: Check if config file exists

### LINKED ISSUE #12757: Coder Code Server script overwrite config file
### ✅ Have you read and understood the above guidelines?

yes

### 🔎 Did you run the script with verbose mode enabled?

Yes, verbose mode was enabled and the output is included below

### 📜 What is the name of the script you are using?

Coder Code Server

### 📂 What was the exact command used to execute the script?

bash -c "$(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/tools/addon/coder-code-server.sh)"

### ⚙️ What settings are you using?

- [x] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 13

### 📈 Which Proxmox version are you on?

pve-manager/9.1.6/71482d1833ded40a (running ke rnel: 6.17.9-1-pve)

### 📝 Provide a clear and concise description of the issue.

Hi,

I deployed `Coder Code Server` in a dedicated LXC, but on each update of the app, when running the command again, the `config.yaml` file is overwritten with defaut values.

Would it be possible to check it the file exists and in this case keep it / do not overwrite it ?

Part of the script:
```
mkdir -p ~/.config/code-server/
systemctl enable -q --now code-server@"$USER"
cat <<EOF >~/.config/code-server/config.yaml
bind-addr: 0.0.0.0:8680
auth: none
password: 
cert: false
EOF
```

Thanks and kind regards

### 🔄 Steps to reproduce the issue.

1. Run command inside LXC shell: `bash -c "$(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/tools/addon/coder-code-server.sh)"`.
2. The config file `~/.config/code-server/config.yaml` is overwritten with default values.

### ❌ Paste the full error output (if available).

N/A

### 🖼️ Additional context (optional).

_No response_

### PR DESCRIPTION
**Pull request by michelroegl-brunner**
## ✍️ Description

This PR checks if a config file exists, and if so  dose not overwrite with default values.

## 🔗 Related Issue

Fixes #12757 

## ✅ Prerequisites (**X** in brackets)

- [X] **Self-review completed** – Code follows project standards.
- [X] **Tested thoroughly** – Changes work as expected.
- [X] **No security risks** – No hardcoded secrets, unnecessary privilege escalations, or permission issues.

---

## 🛠️ Type of Change (**X** in brackets)

- [ ] 🐞 **Bug fix** – Resolves an issue without breaking functionality.
- [X] ✨ **New feature** – Adds new, non-breaking functionality.
- [ ] 💥 **Breaking change** – Alters existing functionality in a way that may require updates.
- [ ] 🆕 **New script** – A fully functional and tested script or script set.
- [ ] 🌍 **Website update** – Changes to website-related JSON files or metadata.
- [ ] 🔧 **Refactoring / Code Cleanup** – Improves readability or maintainability without changing functionality.
- [ ] 📝 **Documentation update** – Changes to `README`, `AppName.md`, `CONTRIBUTING.md`, or other docs.

### CODE REVIEW

File: tools/addon/coder-code-server.sh [hunk 1]
```diff
@@ -89,17 +89,26 @@ VERSION=$(curl -fsSL https://api.github.com/repos/coder/code-server/releases/lat
   awk '{print substr($2, 3, length($2)-4) }')
 
 msg_info "Installing Code-Server v${VERSION}"
+
```
Comment (tremor021) [inline tools/addon/coder-code-server.sh:92]:
```suggestion
```

**Review by tremor021 — APPROVED** [review]

**Review by CrazyWolf13 — APPROVED** [review]

**Comment by crivchri** [comment]
Hi @michelroegl-brunner,

I just tried the updated script, but it returns an error:

```
   ______          __        _____                          
  / ____/___  ____/ /__     / ___/___  ______   _____  _____
 / /   / __ \/ __  / _ \    \__ \/ _ \/ ___/ | / / _ \/ ___/
/ /___/ /_/ / /_/ /  __/   ___/ /  __/ /   | |/ /  __/ /    
\____/\____/\__,_/\___/   /____/\___/_/    |___/\___/_/     
 
This will Install Coder Code Server on code-server. Proceed(y/n)?y
 ✓ Installed Dependencies
 - Installing Code-Server v4.110.1...bash: line 94: existing_config: command not found
‼ ERROR 127@94 Unknown failure occured.
root@code-server:~# 
```

Thank you in advance for your help.

Kind regards
