### PR TITLE
Fix: Element Synapse - Fixed server listening on both localhost and 0.0.0.0

### LINKED ISSUE #2374: Element Synapse LXC script should restart the service after sed
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

elementsynapse

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/elementsynapse.sh)"

### 📝 Provide a clear and concise description of the issue.

After installation the service comes up listening on localhost as it starts before the sed lines get run. This would likely be simplest to fix by auto restarting the service afterwards.

### ⚙️ What settings are you using?

- [x] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

1. bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/elementsynapse.sh)"
2. Connect to <ip>:8008 gives connection refused
3. systemctl restart matrix-synapse
4. Connection now works

### ❌ Paste the full error output (if available).

Connection refused

### 🖼️ Additional context (optional).

_No response_

### PR DESCRIPTION
**Pull request by tremor021**
## 🔗 Related PR / Discussion / Issue  
Link: #2374 

## ✅ Prerequisites  
Before this PR can be reviewed, the following must be completed:  
- [✅] **Self-review performed** – Code follows established patterns and conventions.  
- [✅] **Testing performed** – Changes have been thoroughly tested and verified.  

## 🛠️ Type of Change  
Select all that apply:  
- [✅] 🐞 **Bug fix** – Resolves an issue without breaking functionality.  
- [] ✨ **New feature** – Adds new, non-breaking functionality.  
- [] 💥 **Breaking change** – Alters existing functionality in a way that may require updates.  
- [] 🆕 **New script** – A fully functional and tested script or script set.

### CODE REVIEW

File: install/elementsynapse-install.sh [hunk 1]
```diff
@@ -26,12 +26,13 @@ msg_ok "Installed Dependencies"
...
+wget -q -O /usr/share/keyrings/matrix-org-archive-keyring.gpg https://packages.matrix.org/debian/matrix-org-archive-keyring.gpg
+echo "deb [signed-by=/usr/share/keyrings/matrix-org-archive-keyring.gpg] https://packages.matrix.org/debian/ $(lsb_release -cs) main" >/etc/apt/sources.list.d/matrix-org.list
 $STD apt-get update
 echo "matrix-synapse-py3 matrix-synapse/server-name string $servername" | debconf-set-selections
 echo "matrix-synapse-py3 matrix-synapse/report-stats boolean false" | debconf-set-selections
 $STD apt-get install matrix-synapse-py3 -y
+systemctl stop matrix-synapse
 sed -i 's/127.0.0.1/0.0.0.0/g' /etc/matrix-synapse/homeserver.yaml
 sed -i 's/'\''::1'\'', //g' /etc/matrix-synapse/homeserver.yaml
 systemctl enable -q --now matrix-synapse
```
Comment (michelroegl-brunner) [inline install/elementsynapse-install.sh:38]: Could this be a simple, systemctl start `matrix-synapse` , as i guess the service file is created during installation?

Comment (tremor021) [reply install/elementsynapse-install.sh:38]: deb creates and starts the server, i didn't catch that before. this makes it listen to the pre-sed address, which is 127.0.0.1 and systemctl --now brings another copy up that listens on post-sed address, which is 0.0.0.0. So the safest thing to do is to stop the service, do the sed and bring a fresh instance up.

Comment (michelroegl-brunner) [reply install/elementsynapse-install.sh:38]: Yes, but systemctl enable -q --now would be redundent and could be a more simple systemctl start.

**Review by michelroegl-brunner — APPROVED** [review]

**Review by bvdberg01 — APPROVED** [review]
