### PR TITLE
Slskd: Remove stale Soularr lock file on startup and redirect logs to stderr

### LINKED ISSUE #13657: Handle Soularr lock file on ungraceful exit in slskd script
### ✅ Have you read and understood the above guidelines?

yes

### 🔎 Did you run the script with verbose mode enabled?

Yes, verbose mode was enabled and the output is included below

### 📜 What is the name of the script you are using?

Slskd

### 📂 What was the exact command used to execute the script?

systemctl enable soularr.timer

### ⚙️ What settings are you using?

- [x] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 13

### 📈 Which Proxmox version are you on?

pve-manager/8.2.4/faa83925c9641325 (running kernel: 6.8.8-4-pve)

### 📝 Provide a clear and concise description of the issue.

After installing script and configuring everything correctly, and enabling the slskd & soularr service, if for any reason the soularr Python script exits with an unhandled error, the lock file will persist. This will give a headache for anyone that has to debug it since the log files for this issue don't appear in journalctl for some reason.

### 🔄 Steps to reproduce the issue.

Step 1. Run the soularr script via `systemctl start soularr` or `systemctl enable soularr.timer`
Step 2. Make lidarr or slskd unreachable for any reason so that the soularr script errors out and gets deactivated
Step 3. Check that the lock file, which is prefixed with a `.` (and therefore hidden) is in your folder via `ls /opt/soularr/.soularr.lock`
Step 4. Try to start the script, it will exit immediately, and there will not be any logs in journalctl

### ❌ Paste the full error output (if available).

<details>
<summary>Journalctl silent shutdown</summary>

> ░░ Apr 11 17:44:32 slskd systemd[1]: Started soularr.service - Soularr service. 
> ░░ Subject: A start job for unit soularr.service has finished successfully 
> ░░ Defined-By: systemd 
> ░░ Support: https://www.debian.org/support 
> ░░ 
> ░░ A start job for unit soularr.service has finished successfully. 
> ░░ 
> ░░ The job identifier is 2145. Apr 11 17:44:32 slskd systemd[1]: soularr.service: Main process exited, code=exited, status=1/FAILURE 
> ░░ Subject: Unit process exited 
> ░░ Defined-By: systemd 
> ░░ Support: https://www.debian.org/support 
> ░░ 
> ░░ An ExecStart= process belonging to unit soularr.service has exited. 
> ░░ 
> ░░ The process' exit code is 'exited' and its exit status is 1. Apr 11 17:44:32 slskd systemd[1]: soularr.service: Failed with result 'exit-code'. 
> ░░ Subject: Unit failed 
> ░░ Defined-By: systemd 
> ░░ Support: https://www.debian.org/support 
> ░░ 
> ░░ The unit soularr.service has entered the 'failed' state with result

</details>

For some reason the logger does not output anything, even when running either the run.sh script or the uv run soularr.py directly.
``` py
if not is_docker() and os.path.exists(lock_file_path) and args.lock_file:
        logger.info(f"Soularr instance is already running.")
        sys.exit(1)
```
</details>

### 🖼️ Additional context (optional).

This is handled by soularr by putting the lockfile in a temporary directory (mrusse/soularr#16), which gets erased by virtue of  docker shutting down. This doesn't happen in our LXC because the LXC persists.

### PR DESCRIPTION
**Pull request by MickLesk**
## 🔗 Related Issue

Fixes #13657

## ✅ Prerequisites (**X** in brackets)

- [x] **Self-review completed** – Code follows project standards.
- [ ] **Tested thoroughly** – Changes work as expected.
- [x] **No security risks** – No hardcoded secrets, unnecessary privilege escalations, or permission issues.

---

## 🛠️ Type of Change (**X** in brackets)

- [x] 🐞 **Bug fix** – Resolves an issue without breaking functionality.
- [ ] ✨ **New feature** – Adds new, non-breaking functionality.
- [ ] 💥 **Breaking change** – Alters existing functionality in a way that may require updates.
- [ ] 🆕 **New script** – A fully functional and tested script or script set.
- [ ] 🌍 **Website update** – Changes to website-related JSON files or metadata.
- [ ] 🔧 **Refactoring / Code Cleanup** – Improves readability or maintainability without changing functionality.
- [ ] 📝 **Documentation update** – Changes to `README`, `AppName.md`, `CONTRIBUTING.md`, or other docs.

### CODE REVIEW

File: install/slskd-install.sh [hunk 1]
```diff
@@ -47,13 +47,18 @@ if [[ ${soularr,,} =~ ^(y|yes)$ ]]; then
...
-  echo "Soularr is already running. Exiting..."
+  echo "Soularr is already running. Exiting..." >&2
   exit 1
-else
-  source /opt/soularr/venv/bin/activate
-  uv run python3 -u /opt/soularr/soularr.py --config-dir /opt/soularr
 fi
+
+# Remove stale lock file from previous ungraceful exit
+rm -f "\$LOCK_FILE"
```
Comment (CrazyWolf13) [inline install/slskd-install.sh]:
```suggestion
if ps aux | grep "[s]oularr.py" >/dev/null; then
  echo "Soularr is already running. Exiting..." >&2
 exit 1
fi

# Remove stale lock file from previous ungraceful exit
rm -f "/opt/soularr/.soularr.lock"
```

**Review by CrazyWolf13 — CHANGES_REQUESTED** [review]

File: install/slskd-install.sh (hunk 1 above)
Comment (CrazyWolf13) [reply install/slskd-install.sh]: weird commit suggestion, just meant to remove the extra LOCK_FILE var

Comment (MickLesk) [reply install/slskd-install.sh]: image

your suggestion is broken for me, it looks all good in source?

Comment (MickLesk) [reply install/slskd-install.sh]: image

**Review by CrazyWolf13 — APPROVED** [review]

**Review by vhsdream — APPROVED** [review]
