### PR TITLE
Fix: Update-Script Firefly III based on their docs

### LINKED ISSUE #2533: Firefly III update function broken
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

firefly.sh

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/firefly.sh)"

### 📝 Provide a clear and concise description of the issue.

Using the update function within the LXC container doesn't work and breaks the application

### ⚙️ What settings are you using?

- [x] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

Using update function within the LXC Container

### ❌ Paste the full error output (if available).

  ✔️  Stopped Apache2
 ⠸ Updating Firefly to v6.2.7 
[ERROR] in line 45: exit code 0: while executing command composer install --no-dev --no-interaction &> /dev/null

### 🖼️ Additional context (optional).

_No response_

### PR DESCRIPTION
**Pull request by MickLesk**
## ✍️ Description  
Firefly III changed there Docs 2 days ago.
 
Some Commands are removed and renamed 

## 🔗 Related PR / Discussion / Issue  
Link: #2533 
https://docs.firefly-iii.org/how-to/firefly-iii/upgrade/self-managed/

## ✅ Prerequisites  
Before this PR can be reviewed, the following must be completed:  
- [x] **Self-review performed** – Code follows established patterns and conventions.  
- [x] **Testing performed** – Changes have been thoroughly tested and verified.  

## 🛠️ Type of Change  
Select all that apply:  
- [x] 🐞 **Bug fix** – Resolves an issue without breaking functionality.  
- [] ✨ **New feature** – Adds new, non-breaking functionality.  
- [] 💥 **Breaking change** – Alters existing functionality in a way that may require updates.  
- [] 🆕 **New script** – A fully functional and tested script or script set.

### CODE REVIEW

**Review by tremor021 — DISMISSED** [review]

**Comment by MickLesk** [comment]
dont merge yet, need to be tested locally. fireflys docu is crap

File: ct/firefly.sh [hunk 1]
```diff
@@ -42,13 +42,13 @@ check_container_resources
     wget -q "https://github.com/firefly-iii/firefly-iii/releases/download/v${RELEASE}/FireflyIII-v${RELEASE}.tar.gz"
     tar -xzf FireflyIII-v${RELEASE}.tar.gz -C /opt/firefly --exclude='storage'
     cd /opt/firefly 
-    composer install --no-dev --no-interaction &>/dev/null
+    #composer install --no-dev --no-interaction &>/dev/null
```
Comment (jesserockz) [inline ct/firefly.sh:45]: While you are at it, the storage folder is never copied back after being copied and wiped out 6 lines above, causing other issues
```suggestion
    cp -r /opt/storage /opt/firefly/storage
    #composer install --no-dev --no-interaction &>/dev/null
```

Comment (MickLesk) [reply ct/firefly.sh:45]: > While you are at it, the storage folder is never copied back after being copied and wiped out 6 lines above, causing other issues
> ```suggestion
>     cp -r /opt/storage /opt/firefly/storage
>     #composer install --no-dev --no-interaction &>/dev/null
> ```

Will be never removed. Its exluded in tarfile

**Review by tremor021 — APPROVED** [review]

**Review by michelroegl-brunner — APPROVED** [review]

**Review by CrazyWolf13 — APPROVED** [review]
