### PR TITLE
SigNoz: Fix wrong URL for Zookeeper

### LINKED ISSUE #7739: SigNoz Error during install
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

SigNoz

### 📂 What was the exact command used to execute the script?

bash -c "$(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/ct/signoz.sh)"

### ⚙️ What settings are you using?

- [x] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 📈 Which Proxmox version are you on?

9

### 📝 Provide a clear and concise description of the issue.

I ran the script and got this error at the end

Synchronizing state of clickhouse-server.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable clickhouse-server
Created symlink /etc/systemd/system/multi-user.target.wants/clickhouse-server.service → /lib/systemd/system/clickhouse-server.service.
Setting up clickhouse-client (25.8.4.13) ...
  ✔️   Setup ClickHouse
  ⏳   Setting up Zookeepercurl: (22) The requested URL returned error: 404

[ERROR] in line 33: exit code 0: while executing command curl -fsSL "https://dlcdn.apache.org/zookeeper/zookeeper-3.8.4/apache-zookeeper-3.8.4-bin.tar.gz" -o "$HOME/zookeeper.tar.gz"

[ERROR] in line 1345: exit code 0: while executing command lxc-attach -n "$CTID" -- bash -c "$(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/install/${var_install}.sh)"

### 🔄 Steps to reproduce the issue.

Ran the script in PVE9 shell

### ❌ Paste the full error output (if available).

Synchronizing state of clickhouse-server.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable clickhouse-server
Created symlink /etc/systemd/system/multi-user.target.wants/clickhouse-server.service → /lib/systemd/system/clickhouse-server.service.
Setting up clickhouse-client (25.8.4.13) ...
  ✔️   Setup ClickHouse
  ⏳   Setting up Zookeepercurl: (22) The requested URL returned error: 404

[ERROR] in line 33: exit code 0: while executing command curl -fsSL "https://dlcdn.apache.org/zookeeper/zookeeper-3.8.4/apache-zookeeper-3.8.4-bin.tar.gz" -o "$HOME/zookeeper.tar.gz"

[ERROR] in line 1345: exit code 0: while executing command lxc-attach -n "$CTID" -- bash -c "$(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/install/${var_install}.sh)"

### 🖼️ Additional context (optional).

_No response_

### PR DESCRIPTION
**Pull request by tremor021**
## ✍️ Description  
- Apache Zookeper no longer hosts v3.8.4 on their servers. We switch to the latest release.

## 🔗 Related PR / Issue  
Link: #7739 

## ✅ Prerequisites  (**X** in brackets) 

- [x] **Self-review completed** – Code follows project standards.  
- [x] **Tested thoroughly** – Changes work as expected.  
- [x] **No security risks** – No hardcoded secrets, unnecessary privilege escalations, or permission issues.  

---

## 🛠️ Type of Change (**X** in brackets)  

- [x] 🐞 **Bug fix** – Resolves an issue without breaking functionality.  
- [ ] ✨ **New feature** – Adds new, non-breaking functionality.  
- [ ] 💥 **Breaking change** – Alters existing functionality in a way that may require updates.  
- [ ] 🆕 **New script** – A fully functional and tested script or script set.  
- [ ] 🌍 **Website update** – Changes to website-related JSON files or metadata.  
- [ ] 🔧 **Refactoring / Code Cleanup** – Improves readability or maintainability without changing functionality.  
- [ ] 📝 **Documentation update** – Changes to `README`, `AppName.md`, `CONTRIBUTING.md`, or other docs.

### CODE REVIEW

**Review by MickLesk — DISMISSED** [review]

File: install/signoz-install.sh [hunk 1]
```diff
@@ -30,12 +30,12 @@ $STD apt-get install -y clickhouse-server clickhouse-client
 msg_ok "Setup ClickHouse"
 
 msg_info "Setting up Zookeeper"
-curl -fsSL "https://dlcdn.apache.org/zookeeper/zookeeper-3.8.4/apache-zookeeper-3.8.4-bin.tar.gz" -o "$HOME/zookeeper.tar.gz"
+curl -fsSL "https://dlcdn.apache.org/zookeeper/current/$(curl -fsSL https://dlcdn.apache.org/zookeeper/current/ | grep -o 'apache-zookeeper-[0-9.]\+-bin\.tar\.gz' | head -n1)" -o ~/zookeeper.tar.gz
```
Comment (michelroegl-brunner) [inline install/signoz-install.sh]: Thats a bit of a messey Line tbh. Can you factor that curl/crep in a variable so its a bit more readable?

**Review by michelroegl-brunner — CHANGES_REQUESTED** [review]

File: install/signoz-install.sh (hunk 1 above)
Comment (tremor021) [reply install/signoz-install.sh]: This guy making me do extra work... Check it now

**Review by michelroegl-brunner — APPROVED** [review]
Thanks mate!

**Review by MickLesk — APPROVED** [review]
