### PR TITLE
Technitium DNS: Fix update

### LINKED ISSUE #8978: Technitium Version 14.0 update needs to install dotnet runtime 9.0
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Technitium

### 📂 What was the exact command used to execute the script?

update

### ⚙️ What settings are you using?

- [x] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 📈 Which Proxmox version are you on?

pve-manager/9.0.11/3bf5476b8a4699e2 (running kernel: 6.14.11-4-pve)

### 📝 Provide a clear and concise description of the issue.

The install script manually installs DotNet 8 but the upgrade script does not update dotnet runtime to v9.0

according to the [changelog for v14.0](https://github.com/TechnitiumSoftware/DnsServer/blob/master/CHANGELOG.md):

>  Upgraded codebase to use .NET 9 runtime. If you had manually installed the DNS Server or .NET 8 Runtime earlier then you must install .NET 9 Runtime manually before upgrading the DNS server.

### 🔄 Steps to reproduce the issue.

1. Open a shell on the technitium lxc
2. type update
3. wait for it to finish updating
4. restart lxc or `sudo systemctl restart dns`

### ❌ Paste the full error output (if available).

from `journalctl`

```
Nov 08 22:34:25 dns dns-server[475]: You must install or update .NET to run this application.
Nov 08 22:34:25 dns dns-server[475]: App: /opt/technitium/dns/DnsServerApp.dll
Nov 08 22:34:25 dns dns-server[475]: Architecture: x64
Nov 08 22:34:25 dns dns-server[475]: Framework: 'Microsoft.NETCore.App', version '9.0.0' (x64)
Nov 08 22:34:25 dns dns-server[475]: .NET location: /usr/share/dotnet/
Nov 08 22:34:25 dns dns-server[475]: The following frameworks were found:
Nov 08 22:34:25 dns dns-server[475]:   8.0.12 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
Nov 08 22:34:25 dns dns-server[475]: Learn more:
Nov 08 22:34:25 dns dns-server[475]: https://aka.ms/dotnet/app-launch-failed
Nov 08 22:34:25 dns dns-server[475]: To install missing framework, download:
Nov 08 22:34:25 dns dns-server[475]: https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version>
Nov 08 22:34:25 dns systemd[1]: Started dns.service - Technitium DNS Server.
Nov 08 22:34:25 dns systemd[1]: dns.service: Main process exited, code=exited, status=150/n/a
Nov 08 22:34:25 dns systemd[1]: dns.service: Failed with result 'exit-code'.
Nov 08 22:34:35 dns systemd[1]: dns.service: Scheduled restart job, restart counter is at 52.
Nov 08 22:34:35 dns systemd[1]: Stopped dns.service - Technitium DNS Server.
```

### 🖼️ Additional context (optional).

the following allowed me to get technitium back up
```bash
$ apt install -y aspnetcore-runtime-9.0
$ sudo systemctl restart dns
```

### PR DESCRIPTION
**Pull request by tremor021**
## ✍️ Description  
- Fix dependency for Technitium DNS v14.0

## 🔗 Related PR / Issue  
Link: #8978 

## ✅ Prerequisites  (**X** in brackets) 

- [x] **Self-review completed** – Code follows project standards.  
- [x] **Tested thoroughly** – Changes work as expected.  
- [x] **No security risks** – No hardcoded secrets, unnecessary privilege escalations, or permission issues.  

---

## 🛠️ Type of Change (**X** in brackets)  

- [x] 🐞 **Bug fix** – Resolves an issue without breaking functionality.  
- [ ] ✨ **New feature** – Adds new, non-breaking functionality.  
- [ ] 💥 **Breaking change** – Alters existing functionality in a way that may require updates.  
- [ ] 🆕 **New script** – A fully functional and tested script or script set.  
- [ ] 🌍 **Website update** – Changes to website-related JSON files or metadata.  
- [ ] 🔧 **Refactoring / Code Cleanup** – Improves readability or maintainability without changing functionality.  
- [ ] 📝 **Documentation update** – Changes to `README`, `AppName.md`, `CONTRIBUTING.md`, or other docs.

### CODE REVIEW

**Review by MickLesk — DISMISSED** [review]

File: install/technitiumdns-install.sh [hunk 1]
```diff
@@ -31,15 +31,9 @@ msg_ok "Installed Technitium DNS"
...
 cp /opt/technitium/dns/systemd.service /etc/systemd/system/technitium.service
-systemctl enable -q --now technitium
+systemctl enable -q --now technitium 
 msg_ok "Service created"
 
 motd_ssh
 customize
-
-msg_info "Cleaning up"
-rm -f /opt/DnsServerPortable.tar.gz
```
Comment (CrazyWolf13) [inline install/technitiumdns-install.sh:41]: keep this or move to tmp for it to be still cleared?

**Review by CrazyWolf13 — CHANGES_REQUESTED** [review]

**Review by MickLesk — APPROVED** [review]

**Review by CrazyWolf13 — APPROVED** [review]

**Comment by DJKatastrof** [comment]
I'm trying to update to 14.1, but it won't, it just says it's "successful".

image

**Comment by CrazyWolf13** [comment]
@DJKatastrof seems like everything worked, no?

Create an issue otherwise.

**Comment by DJKatastrof** [comment]
Didn't notice this was the pull request.. sorry
