### PR TITLE
Fix `rm` bug in Vikunja update

### LINKED ISSUE #684: Vikunja Script Update Dropped Config
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I updated vikunja using the update command and it delete my config.  I had to restore from backup.

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

_No response_

### Please provide detailed steps to reproduce the issue.

Type update.

restart lxc
try to login, can't user doesn't exist
rollback

### PR DESCRIPTION
**Pull request by michelroegl-brunner**
> [!NOTE]
> We are meticulous when it comes to merging code into the main branch, so please understand that we may reject pull requests that do not meet the project's standards. It's never personal. Also, game-related scripts have a lower chance of being merged.

## Description

Fixes an Issue with old installs where /opt/* is delete. Changed so only the binary is deleted, not all foldres.

Fixes #684

## Type of change
Please check the relevant option(s):

- [X] Bug fix (non-breaking change that resolves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (a fix or feature that would cause existing functionality to change unexpectedly)
- [ ] New script (a fully functional and thoroughly tested script or set of scripts.)

## Prerequisites
The following efforts must be made for the PR to be considered. Please check when completed:
- [X] Self-review performed (I have reviewed my code, ensuring it follows established patterns and conventions)
- [X] Testing performed (I have tested my changes, ensuring everything works as expected)
- [X] Documentation updated (I have updated any relevant documentation)

## Additional Information (optional)
Provide any additional context or screenshots about the feature or fix here.

## Related Pull Requests / Discussions

If there are other pull requests or discussions related to this change, please link them here:

### CODE REVIEW

File: ct/vikunja.sh [hunk 1]
```diff
@@ -67,7 +67,7 @@ if [[ ! -f /opt/${APP}_version.txt ]] || [[ "${RELEASE}" != "$(cat /opt/${APP}_v
 
   msg_info "Updating ${APP} to ${RELEASE}"
   cd /opt
-  rm -rf /opt/*
+  rm -r /opt/vikunja/vikunja
```
Comment (havardthom) [inline ct/vikunja.sh:70]:
```suggestion
  rm -rf /opt/vikunja/vikunja
```
Add `f` to avoid crash if it file does not exist. Recursive `r` option is not really needed, but better to just have it on every rm, so if someone copies it for a folder we don't have to correct them

Comment (michelroegl-brunner) [reply ct/vikunja.sh]: You are right, is changed.

**Review by havardthom — APPROVED** [review]

**Review by MickLesk — APPROVED** [review]
