### PR TITLE
librenms: Fix password to short

### LINKED ISSUE #9233: LibreNMS Install Error
### ✅ Have you read and understood the above guidelines?

Yes

### 📜 What is the name of the script you are using?

LibreNMS

### 📂 What was the exact command used to execute the script?

bash -c "$(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/ct/librenms.sh)"

### ⚙️ What settings are you using?

- [x] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 13

### 📈 Which Proxmox version are you on?

pve-manager/9.0.11/3bf5476b8a4699e2 (running kernel: 6.14.11-4-pve)

### 📝 Provide a clear and concise description of the issue.

Error while installation using the installscript with the shell or the local version of PVE Community Scripts

### 🔄 Steps to reproduce the issue.

Use the Install Script with default settings

### ❌ Paste the full error output (if available).

  ⚙️  Using Default Settings on node pve-03
  🆔  Container ID: 124
  🖥️  Operating System: debian (13)
  📦  Container Type: Unprivileged
  💾  Disk Size: 4 GB
  🧠  CPU Cores: 2
  🛠️  RAM Size: 2048 MiB
  🚀  Creating a LibreNMS LXC using the above default settings
  
  ✔️   Storage local (Free: 55.7GB  Used: 8.5GB) [Template]
  ✔️   Storage local-lvm (Free: 46.5GB  Used: 80.8GB) [Container]
  ✔️   Template debian-13-standard_13.1-2_amd64.tar.zst [local]
  ✔️   LXC Container 124 was successfully created.
  ✔️   Started LXC Container
  ✔️   Network in LXC is reachable (ping)
  ✔️   Customized LXC Container
  ✔️   Set up Container OS
  ✔️   Network Connected: 10.30.14.27 
  ✔️   IPv4 Internet Connected
   ✖️   IPv6 Internet Not Connected
  ✔️   Git DNS: github.com:(✔️ ) raw.githubusercontent.com:(✔️ ) api.github.com:(✔️ ) git.community-scripts.org:(✔️ )
  ✔️   Updated Container OS
  ✔️   Installed Dependencies
  ✔️   Installed Python Dependencies
  ✔️   Setup PHP 8.4
  ✔️   Setup MariaDB 12.1.1
  ✔️   Setup Composer
  ✔️   Python 3.13 installed
  ✔️   Setup uv 0.9.9
  ✔️   Set up MariaDB Database
  ✔️   Deployed: librenms (25.11.0)
  ✔️   Configured LibreNMS
  ✔️   Configured MariaDB
  ✔️   Configured PHP-FPM
  ✔️   Configured Nginx
⠋ Configure Services
[ERROR] in line 159: exit code 0: while executing command "$@" > /dev/null 2>&1
/tmp/functions.sh: line 5207: post_update_to_api: command not found

[ERROR] in line 1382: exit code 0: while executing command lxc-attach -n "$CTID" -- bash "$INSTALL_SCRIPT_FILE"

[17:54:45] ✅ SSH script execution finished with code: 127

### 🖼️ Additional context (optional).

_No response_

### PR DESCRIPTION
**Pull request by michelroegl-brunner**
## 🔗 Related PR / Issue  
Link: #

## ✅ Prerequisites  (**X** in brackets) 

- [ ] **Self-review completed** – Code follows project standards.  
- [ ] **Tested thoroughly** – Changes work as expected.  
- [ ] **No security risks** – No hardcoded secrets, unnecessary privilege escalations, or permission issues.  

---

## 🛠️ Type of Change (**X** in brackets)  

- [ ] 🐞 **Bug fix** – Resolves an issue without breaking functionality.  
- [ ] ✨ **New feature** – Adds new, non-breaking functionality.  
- [ ] 💥 **Breaking change** – Alters existing functionality in a way that may require updates.  
- [ ] 🆕 **New script** – A fully functional and tested script or script set.  
- [ ] 🌍 **Website update** – Changes to website-related JSON files or metadata.  
- [ ] 🔧 **Refactoring / Code Cleanup** – Improves readability or maintainability without changing functionality.  
- [ ] 📝 **Documentation update** – Changes to `README`, `AppName.md`, `CONTRIBUTING.md`, or other docs.

### CODE REVIEW

**Review by CrazyWolf13 — DISMISSED** [review]

**Comment by CrazyWolf13** [comment]
@michelroegl-brunner why not generate one?

**Comment by michelroegl-brunner** [comment]
Idk, i wanted to keep it simple, but i do that tommorow.

**Review by MickLesk — CHANGES_REQUESTED** [review]
Merge-Block

**Review by MickLesk — DISMISSED** [review]

File: install/librenms-install.sh [hunk 1]
```diff
@@ -113,11 +113,20 @@ mkdir -p /etc/bash_completion.d/
...
 cp /opt/librenms/snmpd.conf.example /etc/snmp/snmpd.conf
 
+APP_PASSWORD=$(openssl rand -base64 18 | tr -dc 'a-zA-Z0-9' | head -c13)
+APP_USER="admin"
+
+cat >~/librenms.creds <<'EOF'
+LibreNMS Admin User Credentials
+Username: ${APP_USER}
+Password: ${APP_PASSWORD}
+EOF
```
Comment (CrazyWolf13) [inline install/librenms-install.sh]: use our default for creds:

https://github.com/community-scripts/ProxmoxVE/blob/main/install/crafty-controller-install.sh#L81-L85

**Review by MickLesk — APPROVED** [review]

**Review by CrazyWolf13 — APPROVED** [review]

**Comment by Lowitle** [comment]
Hello,

I'm having issues with password, I installed this Comunity Script yesterday and I can't log in using admin/admin user/password that says in the description page.

¿How can I resolve that?

**Comment by MickLesk** [comment]
Interesting, and where do you read this? Did you ever read our Page?
