### PR TITLE
Zipline: Add new ENV Variable and Change Update

### LINKED ISSUE #3966: Zipline installer and updater issues - Dataloss
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Zipline

### 📂 What was the exact command used to execute the script?

bash -c "$(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/ct/zipline.sh)"

### ⚙️ What settings are you using?

- [x] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

_No response_

### 📝 Provide a clear and concise description of the issue.

Zip[line v4 - The install script for Zipline puts the user Upload data dir inside of `/opt/zipline` as the default setting (creates /opt/zipline) as the .env does not contain suitable vars to put the data outside of this dir

Example From docs https://zipline.diced.sh/docs/config/datasource : 
```
DATASOURCE_TYPE=local
DATASOURCE_LOCAL_DIRECTORY=./uploads
```

CT script on line 43 contains the following function: `rm -R /opt/zipline`
The recursive remove of this dir removes `/opt/zipline/upload` and thus all user uploaded data
Suggestion to move data to `/opt/zline-uploads` as default config or other suitable location to prevent loss when erasing install for update. Alternative would be to pull from git for install rather than the zip as per official docs https://zipline.diced.sh/docs/get-started/source

**Additionally if using an existing Zipline v3 install** no sanity / safety check is performed when running the upgrade script and v4 being the upgrade version. 
This results in Zipline installation being destroyed incl. uploads dir, and application becoming non-runnable due to database schema changes. 
Suggest adding a sanity check if version is 3 to error back to CLI and stop user upgrading and suggeting they read the documentation for upgrade or install a new CT and restore data export from v3 install.

**Additional Additional**
Dir removal takes place BEFORE downloading update files. If internet connection fails mid update (this happened to me), install becomes non-usable as dir is removed. Running upgrade script again doesnt fix the install as it no longer exists during check and throws "not installed" error.
Suggestion to pull files BEFORE removing data from disk to prevent such failure. All install tasks as far as possible should be run before destructive actions.

### 🔄 Steps to reproduce the issue.

Run Zipline
Upload data
Check data dir
Run upgrade script to new version (modify version txt to a lower version ID to force update for testing)
Check user data again in web app as not existing

### ❌ Paste the full error output (if available).

none

### 🖼️ Additional context (optional).

_No response_

### PR DESCRIPTION
**Pull request by michelroegl-brunner**
## ✍️ Description  

This PR changes the ENV files to move the uploads out of /opt/zipline int /opt/zipline-uploads to protect it from deletion.
Also tries to copy from the old data folder to the new one.

## 🔗 Related PR / Issue  
Link: #3966

## ✅ Prerequisites  (**X** in brackets) 

- [X] **Self-review completed** – Code follows project standards.  
- [X] **Tested thoroughly** – Changes work as expected.  
- [X] **No security risks** – No hardcoded secrets, unnecessary privilege escalations, or permission issues.  

---

## 🛠️ Type of Change (**X** in brackets)  

- [X] 🐞 **Bug fix** – Resolves an issue without breaking functionality.  
- [ ] ✨ **New feature** – Adds new, non-breaking functionality.  
- [ ] 💥 **Breaking change** – Alters existing functionality in a way that may require updates.  
- [ ] 🆕 **New script** – A fully functional and tested script or script set.  
- [ ] 🌍 **Website update** – Changes to website-related JSON files or metadata.  
- [ ] 🔧 **Refactoring / Code Cleanup** – Improves readability or maintainability without changing functionality.  
- [ ] 📝 **Documentation update** – Changes to `README`, `AppName.md`, `CONTRIBUTING.md`, or other docs.

### CODE REVIEW

File: ct/zipline.sh [hunk 1]
```diff
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-source <(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/misc/build.func)
+source <(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVED/main/misc/build.func)
```
Comment (MickLesk) [inline ct/zipline.sh:2]: VE

File: ct/zipline.sh [hunk 2]
```diff
@@ -40,11 +40,13 @@ function update_script() {
 
     msg_info "Updating ${APP} to ${RELEASE}"
     cp /opt/zipline/.env /opt/
-    rm -R /opt/zipline
+    mkdir -p /opt/zipline-updload
```
Comment (MickLesk) [inline ct/zipline.sh:43]: Spell issue

File: ct/zipline.sh [hunk 3]
```diff
@@ -40,11 +40,13 @@ function update_script() {
...
+    $STD cp -R /opt/zipline/updload/* /opt/zipline-upload/ || true
```
Comment (MickLesk) [inline ct/zipline.sh:44]: Remove the || true of Shellcheck, it Breaks Sometimes Scripts. Cp doesnt need Std?

File: install/zipline-install.sh [hunk 4]
```diff
@@ -50,19 +50,22 @@ echo -e "Zipline Secret: $SECRET_KEY" >>~/zipline.creds
 msg_ok "Set up PostgreSQL"
 
 msg_info "Installing Zipline (Patience)"
-cd /opt
+cd /opt || exit
```
Comment (MickLesk) [inline install/zipline-install.sh:53]: Remove

File: install/zipline-install.sh [hunk 5]
```diff
@@ -50,19 +50,22 @@ echo -e "Zipline Secret: $SECRET_KEY" >>~/zipline.creds
...
 RELEASE=$(curl -fsSL https://api.github.com/repos/diced/zipline/releases/latest | grep "tag_name" | awk '{print substr($2, 3, length($2)-4) }')
 curl -fsSL "https://github.com/diced/zipline/archive/refs/tags/v${RELEASE}.zip" -o $(basename "https://github.com/diced/zipline/archive/refs/tags/v${RELEASE}.zip")
-unzip -q v${RELEASE}.zip
-mv zipline-${RELEASE} /opt/zipline
-cd /opt/zipline
+unzip -q v"${RELEASE}".zip
+mv zipline-"${RELEASE}" /opt/zipline
+cd /opt/zipline || exit
```
Comment (MickLesk) [inline install/zipline-install.sh:58]: Remove Exit

**Review by MickLesk — CHANGES_REQUESTED** [review]

**Review by tremor021 — DISMISSED** [review]

File: ct/zipline.sh [hunk 6]
```diff
@@ -40,10 +40,12 @@ function update_script() {
 
     msg_info "Updating ${APP} to ${RELEASE}"
     cp /opt/zipline/.env /opt/
-    rm -R /opt/zipline
+    mkdir -p /opt/zipline-upload
+    cp -R /opt/zipline/updload/* /opt/zipline-upload/
```
Comment (MickLesk) [inline ct/zipline.sh:44]: /upload/*

File: ct/zipline.sh [hunk 7]
```diff
@@ -40,10 +40,12 @@ function update_script() {
...
     curl -fsSL "https://github.com/diced/zipline/archive/refs/tags/v${RELEASE}.zip" -o $(basename "https://github.com/diced/zipline/archive/refs/tags/v${RELEASE}.zip")
```
Comment (MickLesk) [inline ct/zipline.sh:45]: Maybe an -o v{RELEASE}.zip instead of basename?

File: install/zipline-install.sh [hunk 8]
```diff
@@ -53,16 +53,19 @@ msg_info "Installing Zipline (Patience)"
...
+mv zipline-"${RELEASE}" /opt/zipline
 cd /opt/zipline
 cat <<EOF >/opt/zipline/.env
 DATABASE_URL=postgres://$DB_USER:$DB_PASS@localhost:5432/$DB_NAME
 CORE_SECRET=$SECRET_KEY
 CORE_HOSTNAME=0.0.0.0
 CORE_PORT=3000
 CORE_RETURN_HTTPS=false
+DATASOURCE_TYPE=local
+DATASOURCE_LOCAL_DIRECTORY=/opt/zipline-uploads
```
Comment (MickLesk) [inline install/zipline-install.sh:66]: upload, not uploads?

File: install/zipline-install.sh [hunk 9]
```diff
@@ -53,16 +53,19 @@ msg_info "Installing Zipline (Patience)"
...
 EOF
+mkdir -p /opt/zipline-uploads
```
Comment (MickLesk) [inline install/zipline-install.sh:68]: upload Not Uploads? (Different to ct.sh)

**Review by MickLesk — CHANGES_REQUESTED** [review]

File: ct/zipline.sh (hunk 7 above)
Comment (michelroegl-brunner) [reply ct/zipline.sh:45]: That hase been here befor, i did not want to touch it.

**Review by MickLesk — APPROVED** [review]

**Review by tremor021 — APPROVED** [review]
