### PR TITLE
Fix: file replacement in Watcharr Update Script

### LINKED ISSUE #2497: Watcharr Update Script does not update application
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Watcharr

### 📂 What was the exact command used to execute the script?

update

### 📝 Provide a clear and concise description of the issue.

The script returns a success, but the extracted data (a folder named "Watcharr_2.0.2") will be placed inside the application folder, instead of replacing its contents.
This leads to an updated Watcharr_version.txt, but not to a updated Watcharr app.

### ⚙️ What settings are you using?

- [x] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

1. Have Watcharr installed with the appropriated install script from the helper-script website + have an outdated version of Watcharr (e.g. 2.0.1 or lower)
2. Start update by typing "update" inside the LXC
3. After success: Compare version in /opt/Watcharr_version.txt with the version in /opt/watcharr/package.json

### ❌ Paste the full error output (if available).

No error visible. The script passes without any errors.

### 🖼️ Additional context (optional).

_No response_

### PR DESCRIPTION
**Pull request by Clusters**
## ✍️ Description  
Fixes following: Updated files are moved into a subdirectory instead of replacing old files. The script won't report an error and set the new version, but Watcharr will stay on the old state.

## 🔗 Related PR / Discussion / Issue  
Fixes: #2497

## ✅ Prerequisites  
Before this PR can be reviewed, the following must be completed:  
- [x] **Self-review performed** – Code follows established patterns and conventions.  
- [x] **Testing performed** – Changes have been thoroughly tested and verified.  

## 🛠️ Type of Change  
Select all that apply:  
- [x] 🐞 **Bug fix** – Resolves an issue without breaking functionality.  
- [] ✨ **New feature** – Adds new, non-breaking functionality.  
- [] 💥 **Breaking change** – Alters existing functionality in a way that may require updates.  
- [] 🆕 **New script** – A fully functional and tested script or script set.

### CODE REVIEW

File: ct/watcharr.sh [hunk 1]
```diff
@@ -37,11 +37,12 @@ function update_script() {
 
         msg_info "Updating $APP to v${RELEASE}"
         temp_file=$(mktemp)
```
Comment (tremor021) [inline ct/watcharr.sh:39]:
```suggestion
```

File: ct/watcharr.sh [hunk 2]
```diff
@@ -58,6 +59,7 @@ function update_script() {
 
         msg_info "Cleaning Up"
         rm -f ${temp_file}
```
Comment (tremor021) [inline ct/watcharr.sh:61]:
```suggestion
```

**Review by tremor021 — APPROVED** [review]

**Review by MickLesk — APPROVED** [review]
