### PR TITLE
npmplus: graceful timeout for login retrieval

### LINKED ISSUE #10988: NPMPlus stuck at "Retrieving Default Login" step, container still works
### ✅ Have you read and understood the above guidelines?

yes

### 🔎 Did you run the script with verbose mode enabled?

No (this issue will likely be closed automatically)

### 📜 What is the name of the script you are using?

NPMPlus

### 📂 What was the exact command used to execute the script?

bash -c "$(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/ct/npmplus.sh)"

### ⚙️ What settings are you using?

- [ ] Default Settings
- [x] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Alpine

### 📈 Which Proxmox version are you on?

pve-manager/9.1.4/5ac30304265fbd8e (running kernel: 6.17.4-2-pve)

### 📝 Provide a clear and concise description of the issue.

Script gets stuck at the "Retrieving Default Login" step.

However, I was able to open the configured IP on port 81, and created a login via the webinterface. 

So it seems to be working, further testing probably required.

### 🔄 Steps to reproduce the issue.

1. Run install script
2. Advanced Setup
3. All defaults, except for pass, ip, gateway and APT cacher
4. Let it do it's thing
5. Wait for ~20 minutes
6. Kill the script (crtl+C)

### ❌ Paste the full error output (if available).

Message after cancel (ctrl+C)
Interrupted by user (SIGINT)
  ✖️   Installation failed in container 201 (exit code: 130)

Install Log
[install-lxc-201-b1727ae0.log](https://github.com/user-attachments/files/24725154/install-lxc-201-b1727ae0.log)

### 🖼️ Additional context (optional).

_No response_

### PR DESCRIPTION
**Pull request by MickLesk**
## ✍️ Description
- Change msg_error to msg_warn when login not found
- Add helpful user instructions for manual setup
- Script now exits normally instead of appearing stuck

## 🔗 Related Issue

Fixes #10988

## ✅ Prerequisites (**X** in brackets)

- [x] **Self-review completed** – Code follows project standards.
- [x] **Tested thoroughly** – Changes work as expected.
- [x] **No security risks** – No hardcoded secrets, unnecessary privilege escalations, or permission issues.

---

## 🛠️ Type of Change (**X** in brackets)

- [ ] 🐞 **Bug fix** – Resolves an issue without breaking functionality.
- [ ] ✨ **New feature** – Adds new, non-breaking functionality.
- [ ] 💥 **Breaking change** – Alters existing functionality in a way that may require updates.
- [ ] 🆕 **New script** – A fully functional and tested script or script set.
- [ ] 🌍 **Website update** – Changes to website-related JSON files or metadata.
- [x] 🔧 **Refactoring / Code Cleanup** – Improves readability or maintainability without changing functionality.
- [ ] 📝 **Documentation update** – Changes to `README`, `AppName.md`, `CONTRIBUTING.md`, or other docs.

### CODE REVIEW

File: install/npmplus-install.sh [hunk 1]
```diff
@@ -104,21 +105,24 @@ for i in {1..60}; do
...
     PASSWORD_FOUND=1
   fi
 fi
 
 if [[ $PASSWORD_FOUND -eq 0 ]]; then
-  msg_error "Could not retrieve default login after 120s."
-  echo -e "\nYou can manually check the container logs with:\n  docker logs $CONTAINER_ID | grep 'Creating a new user:'\n"
+  msg_warn "Default login not found in logs (this is normal for NPMplus)"
+  msg_custom "💡" "${GN}" "NPMplus creates an admin account on first web access"
+  msg_custom "📋" "${GN}" "Visit http://<IP>:81 and create your admin user"
```
Comment (CrazyWolf13) [inline install/npmplus-install.sh:127]: @MickLesk can't we use ${IP} here?

Then it would be a clickable link

Comment (MickLesk) [reply install/npmplus-install.sh:127]: never tested on alpine

**Review by tremor021 — APPROVED** [review]

**Review by CrazyWolf13 — APPROVED** [review]
