### PR TITLE
fix: note component in json-editor getting out of focus when typing and revert theme switch animation

### LINKED ISSUE #687: JSON-Generator Notes Field
### Please verify that you have read and understood the guidelines.

yes

### What type of issue is this?

Bug

### A clear and concise description of the issue.

Hi @BramSuurdje 

It seems i have found a bug on the JSON Generator when adding Notes.

I have this issue with  Chrome Version 126.0.6478.115 (Official Build) (64-Bit) as well es Edge Version 121.0.2277.106 (64bit). 
Also on iOS 18.2 in Safari.
Mybee you can have a look at it, and i f you need something to reproduce feel free to reach out :)

Michel

### Which browser are you using?

Chrome

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

_No response_

### Please provide detailed steps to reproduce the issue.

The issue is when you type something in the Notes Section in the Note Text field it looses fokus after every Char you enter, i.e You Write the Letter "A", it looses fokus and jumps out of the input field. Then i have to go back in and the cycle repeats.

json-gen

### PR DESCRIPTION
**Pull request by bramsuurdje**
> [!NOTE]
> We are meticulous when it comes to merging code into the main branch, so please understand that we may reject pull requests that do not meet the project's standards. It's never personal. Also, game-related scripts have a lower chance of being merged.

## Description

This pull request includes changes to the Note component in the JSON editor and the removal of certain CSS animations from the global styles.

The theme animation was reverted because it is currently too fast. Slowing it down would negatively affect the user experience (UX). Therefore, the best option is to remove it entirely, as it does not add any value.

Improvements to `Note` component:

* [`frontend/src/app/json-editor/_components/Note.tsx`](diffhunk://#diff-10882bc0495e03a3e2fdf2ba8e3e5ebafef93082d2ff282d581dd591eacaa06aL15-R15): Added `useRef` to manage input references and restore focus after state updates. [[1]](diffhunk://#diff-10882bc0495e03a3e2fdf2ba8e3e5ebafef93082d2ff282d581dd591eacaa06aL15-R15) [[2]](diffhunk://#diff-10882bc0495e03a3e2fdf2ba8e3e5ebafef93082d2ff282d581dd591eacaa06aR30-R31) [[3]](diffhunk://#diff-10882bc0495e03a3e2fdf2ba8e3e5ebafef93082d2ff282d581dd591eacaa06aR54-R59) [[4]](diffhunk://#diff-10882bc0495e03a3e2fdf2ba8e3e5ebafef93082d2ff282d581dd591eacaa06aL61-R78) [[5]](diffhunk://#diff-10882bc0495e03a3e2fdf2ba8e3e5ebafef93082d2ff282d581dd591eacaa06aL100-R113)

The removal of the theme switching animation:

* [`frontend/src/styles/globals.css`](diffhunk://#diff-e6bf1e24da330d7592213bd594a1ab4c81481c6727112f2765ae84c4778d51cfL33-L50): Removed custom animation definitions and related keyframes. [[1]](diffhunk://#diff-e6bf1e24da330d7592213bd594a1ab4c81481c6727112f2765ae84c4778d51cfL33-L50) [[2]](diffhunk://#diff-e6bf1e24da330d7592213bd594a1ab4c81481c6727112f2765ae84c4778d51cfL84-L119)

Fixes #687

## Type of change
Please check the relevant option(s):

- [x] Bug fix (non-breaking change that resolves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (a fix or feature that would cause existing functionality to change unexpectedly)
- [ ] New script (a fully functional and thoroughly tested script or set of scripts.)

## Prerequisites
The following efforts must be made for the PR to be considered. Please check when completed:
- [x] Self-review performed (I have reviewed my code, ensuring it follows established patterns and conventions)
- [x] Testing performed (I have tested my changes, ensuring everything works as expected)
- [ ] Documentation updated (I have updated any relevant documentation)

## Additional Information (optional)
Provide any additional context or screenshots about the feature or fix here.

## Related Pull Requests / Discussions

If there are other pull requests or discussions related to this change, please link them here:
- Related PR #

### CODE REVIEW

**Review by MickLesk — APPROVED** [review]

File: frontend/src/app/json-editor/_components/Note.tsx [hunk 1]
```diff
@@ -49,6 +51,12 @@ function Note({
     setIsValid(result.success);
     setZodErrors(result.success ? null : result.error);
     setScript(updated);
+    // Restore focus after state update
+    if (key === "text") {
+      setTimeout(() => {
```
Comment (havardthom) [inline frontend/src/app/json-editor/_components/Note.tsx:56]: Why does the input field loose focus in the first place? Would it not be better to fix the underlying issue?

Comment (BramSuurdje) [reply frontend/src/app/json-editor/_components/Note.tsx:56]: I don’t know why it’s behaving that way. I’ve tried debugging the issue but haven’t found a solution. This will have to do for now. The page is only used 1–2 times a day, so it’s not worth spending hours debugging it.

**Review by havardthom — APPROVED** [review]
