### PR TITLE
Homarr: bind Redis to localhost only

### LINKED ISSUE #13541: [Homarr] Redis service is exposed to all interfaces
**Script:** [Homarr](https://community-scripts.org/scripts/homarr)

**Reported by:** @Aurelien30000

## Guidelines
- Read and understood guidelines: yes
- Verbose mode used: yes

**Issue occurs during:** Initial Creation / Installation

## Environment
- Linux distribution: Debian
- Proxmox version: 9.1
- Default settings: Yes
- Advanced settings: No
- Exact command: `bash -c "$(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/ct/homarr.sh)"`

## Description
Current installation sets up the `redis-server` with the following configuration (from `homarr` itself):

```
# Directory to store dump.rdb
dir /appdata/redis

# Save the data to disk every 60 seconds if at least 1 key changed
save 60 1
```

Consequently, the  `redis-server` listens to all interfaces (exposed port), i do not think this is adequate for a _standalone_ LXC application:

`tcp       LISTEN     0          511                     [::]:6379                  [::]:*         users:(("redis-server",pid=87,fd=9))`

## Steps to reproduce
1. Install the LXC.
2. Use `ss -tulnp` to see listening interfaces.

## Error output
N/A

## Additional context
TBH, I was wondering to discuss with `homarr` team instead, but in my opinion the need to limit the listening addresses is quite specific to the _standalone_ LXC setup:

```
bind 127.0.0.1 -::1
```

In any case I can forward my request if you do not consider it adequate in your scope.

---

I may also propose the following fix _on your side_.

```diff
diff --git a/ct/homarr.sh b/ct/homarr.sh
index 2b8cf5ded..a4fc6d58f 100644
--- a/ct/homarr.sh
+++ b/ct/homarr.sh
@@ -65,6 +65,7 @@ EOF
 
     msg_info "Updating Homarr"
     cp /opt/homarr/redis.conf /etc/redis/redis.conf
+    echo "bind 127.0.0.1 -::1" >> /etc/redis/redis.conf
     rm /etc/nginx/nginx.conf
     cp /opt/homarr/nginx.conf /etc/nginx/templates/nginx.conf
     msg_ok "Updated Homarr"
diff --git a/install/homarr-install.sh b/install/homarr-install.sh
index e8f199ce2..ff090234c 100644
--- a/install/homarr-install.sh
+++ b/install/homarr-install.sh
@@ -47,6 +47,7 @@ mkdir -p /appdata/redis
 chown -R redis:redis /appdata/redis
 chmod 744 /appdata/redis
 cp /opt/homarr/redis.conf /etc/redis/redis.conf
+echo "bind 127.0.0.1 -::1" >> /etc/redis/redis.conf
 rm /etc/nginx/nginx.conf
 mkdir -p /etc/nginx/templates
 cp /opt/homarr/nginx.conf /etc/nginx/templates/nginx.conf
```

### PR DESCRIPTION
**Pull request by MickLesk**
## 🔗 Related Issue

Fixes #13541

## ✅ Prerequisites (**X** in brackets)

- [x] **Self-review completed** – Code follows project standards.
- [x] **Tested thoroughly** – Changes work as expected.
- [x] **No security risks** – No hardcoded secrets, unnecessary privilege escalations, or permission issues.

---

## 🛠️ Type of Change (**X** in brackets)

- [ ] 🐞 **Bug fix** – Resolves an issue without breaking functionality.
- [x] ✨ **New feature** – Adds new, non-breaking functionality.
- [ ] 💥 **Breaking change** – Alters existing functionality in a way that may require updates.
- [ ] 🆕 **New script** – A fully functional and tested script or script set.
- [ ] 🌍 **Website update** – Changes to website-related JSON files or metadata.
- [ ] 🔧 **Refactoring / Code Cleanup** – Improves readability or maintainability without changing functionality.
- [ ] 📝 **Documentation update** – Changes to `README`, `AppName.md`, `CONTRIBUTING.md`, or other docs.

### CODE REVIEW

File: ct/homarr.sh [hunk 1]
```diff
@@ -65,6 +65,7 @@ EOF
 
     msg_info "Updating Homarr"
     cp /opt/homarr/redis.conf /etc/redis/redis.conf
+    echo "bind 127.0.0.1 -::1" >> /etc/redis/redis.conf
```
Comment (CrazyWolf13) [inline ct/homarr.sh]: only do this once?

Maybe like this?
(untested)
```suggestion
sed -i '/^bind 127\.0\.0\.1 -::1$/!$a bind 127.0.0.1 -::1' /etc/redis/redis.conf
```

**Review by CrazyWolf13 — CHANGES_REQUESTED** [review]

**Review by michelroegl-brunner — APPROVED** [review]

**Review by CrazyWolf13 — APPROVED** [review]
