### PR TITLE
komodo: set `PERIPHERY_CORE_PUBLIC_KEYS` to default value if absent

### LINKED ISSUE #13282: [Komodo] “Periphery requires passkey auth” after v2.0.0 update
### ✅ Have you read and understood the above guidelines?

yes

### 🔎 Did you run the script with verbose mode enabled?

Yes, verbose mode was enabled and the output is included below

### 📜 What is the name of the script you are using?

Komodo

### 📂 What was the exact command used to execute the script?

update

### ⚙️ What settings are you using?

- [x] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 📈 Which Proxmox version are you on?

9.1.6

### 📝 Provide a clear and concise description of the issue.

The update went well, Komodo starts but containers don’t load and it says “Periphery requires passkey auth”.

### 🔄 Steps to reproduce the issue.

Update from v1.19.5 to v2.0.0.

### ❌ Paste the full error output (if available).

```
{
  "id": "68cd2e2216c60ab0d657a9a5",
  "name": "Local",
  "region": null,
  "err": {
    "error": "Periphery requires passkey auth",
    "trace": []
  }
}
```

### 🖼️ Additional context (optional).

_No response_

### PR DESCRIPTION
**Pull request by 4ndv**
## ✍️ Description

After updating Komodo to v2, local periphery agent doesn't get new env variable `PERIPHERY_CORE_PUBLIC_KEYS`, resulting in `Periphery requires passkey auth` error

This PR adds required env from the original `compose.env` found [here](https://komo.do/docs/setup/mongo)

## 🔗 Related Issue

Fixes #13282

## ✅ Prerequisites (**X** in brackets)

- [x] **Self-review completed** – Code follows project standards.
- [x] **Tested thoroughly** – Changes work as expected.
- [x] **No security risks** – No hardcoded secrets, unnecessary privilege escalations, or permission issues.

---

## 🛠️ Type of Change (**X** in brackets)

- [x] 🐞 **Bug fix** – Resolves an issue without breaking functionality.
- [ ] ✨ **New feature** – Adds new, non-breaking functionality.
- [ ] 💥 **Breaking change** – Alters existing functionality in a way that may require updates.
- [ ] 🆕 **New script** – A fully functional and tested script or script set.
- [ ] 🌍 **Website update** – Changes to website-related JSON files or metadata.
- [ ] 🔧 **Refactoring / Code Cleanup** – Improves readability or maintainability without changing functionality.
- [ ] 📝 **Documentation update** – Changes to `README`, `AppName.md`, `CONTRIBUTING.md`, or other docs.

### CODE REVIEW

File: tools/addon/komodo.sh [hunk 1]
```diff
@@ -111,6 +111,12 @@ function update() {
     sed -i '/^KOMODO_PASSKEY=/d' "$COMPOSE_ENV"
   fi
 
+  # === v2 migration: ensure PERIPHERY_CORE_PUBLIC_KEYS is set ===
+  if ! grep -q 'PERIPHERY_CORE_PUBLIC_KEYS' "$COMPOSE_ENV"; then
+    echo '## Use the public key generated by Core.' >> "$COMPOSE_ENV"
+    echo 'PERIPHERY_CORE_PUBLIC_KEYS=file:/config/keys/core.pub' >> "$COMPOSE_ENV"
```
Comment (CrazyWolf13) [inline tools/addon/komodo.sh:117]: isn't normally the syntax something like https:// or file:// ?

Comment (4ndv) [reply tools/addon/komodo.sh:117]: That's exactly how it's set in original compose.env file:

https://github.com/moghtech/komodo/blob/7c95823eb0b12b7909752c06fed800b02ded44a3/compose/compose.env#L39

This line checks for the prefix:

https://github.com/moghtech/komodo/blob/7c95823eb0b12b7909752c06fed800b02ded44a3/bin/periphery/src/state.rs#L128

**Review by CrazyWolf13 — APPROVED** [review]

**Review by MickLesk — APPROVED** [review]
